/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD;

import Controller.CKaryawan;
import Controller.CTable;
import RTClass.Karyawan;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Polman
 */
public class CRUDKaryawan extends javax.swing.JFrame {

    /**
     * Creates new form CRUDKaryawan
     */
    private CKaryawan controllerKaryawan = new CKaryawan();
    private CTable controllerTable = new CTable();
    private DefaultTableModel model = new DefaultTableModel();
    private Karyawan karyawan = new Karyawan();
    
    public CRUDKaryawan() {
        initComponents();
        
        ButtonGroup b = new ButtonGroup();
        b.add(rbKasir);
        b.add(rbDriver);
        rbKasir.setSelected(true);
        
        addColumn();
        addData();
        tableKaryawan.setModel(model);
        clear();
    }
    private void addData(){
        model.getDataVector().removeAllElements();

        model.fireTableDataChanged();
        
        model = controllerTable.addDataKaryawan(model);
        resizeColumnWidth(tableKaryawan);
        clear();
    }
    private void clear(){
        
        txtAlamat.setText("");
        txtEmail.setText("");
        txtHp.setText("");
        txtNama.setText("");
        txtPassword.setText("");
        txtTgl.setDate(new Date(1,1,1));
    }
    private void addColumn(){
        model.addColumn("No");
        model.addColumn("ID Karyawan");
        model.addColumn("Nama");
        model.addColumn("No Hp");
        model.addColumn("Email");
        model.addColumn("Lahir");
        model.addColumn("Alamat");
        model.addColumn("Transaksi");
        model.addColumn("Jabatan");
        model.addColumn("Username");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTgl = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        rbKasir = new javax.swing.JRadioButton();
        rbDriver = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableKaryawan = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnPerbarui = new javax.swing.JButton();
        panelDriver = new javax.swing.JPanel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtLpassword = new javax.swing.JLabel();
        txtLusername = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nama");

        txtNama.setText("maks 25, harus huruf");
        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaKeyTyped(evt);
            }
        });

        jLabel3.setText("No Hp");

        txtHp.setText("maks 13, harus angka");
        txtHp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHpKeyTyped(evt);
            }
        });

        jLabel4.setText("Email");

        txtEmail.setText("maks 30, pake aturan");
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });

        jLabel5.setText("Lahir");

        jLabel6.setText("Alamat");

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        txtAlamat.setText("Maks 100");
        txtAlamat.setMaximumSize(null);
        txtAlamat.setMinimumSize(null);
        txtAlamat.setName(""); // NOI18N
        txtAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlamatKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtAlamat);

        rbKasir.setBackground(new java.awt.Color(0, 204, 204));
        rbKasir.setText("Kasir");

        rbDriver.setBackground(new java.awt.Color(0, 204, 204));
        rbDriver.setText("Driver");
        rbDriver.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbDriverStateChanged(evt);
            }
        });

        jLabel7.setText("Jabatan");

        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/kembaliButton.png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKembali.setIconTextGap(10);
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        tableKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKaryawanMouseClicked(evt);
            }
        });
        tableKaryawan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableKaryawanKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tableKaryawan);

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/tambahButton.png"))); // NOI18N
        btnSimpan.setText("Tambah");
        btnSimpan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSimpan.setIconTextGap(10);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnPerbarui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/ubahButton.png"))); // NOI18N
        btnPerbarui.setText("Perbarui");
        btnPerbarui.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPerbarui.setIconTextGap(10);
        btnPerbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerbaruiActionPerformed(evt);
            }
        });

        panelDriver.setBackground(new java.awt.Color(0, 153, 153));

        txtUsername.setText("maks 25");
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsernameKeyTyped(evt);
            }
        });

        txtPassword.setText("maks 25");
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });

        txtLpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtLpassword.setText("Password");

        txtLusername.setForeground(new java.awt.Color(255, 255, 255));
        txtLusername.setText("Username");

        javax.swing.GroupLayout panelDriverLayout = new javax.swing.GroupLayout(panelDriver);
        panelDriver.setLayout(panelDriverLayout);
        panelDriverLayout.setHorizontalGroup(
            panelDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDriverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLpassword)
                    .addComponent(txtLusername))
                .addGap(15, 15, 15)
                .addGroup(panelDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panelDriverLayout.setVerticalGroup(
            panelDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDriverLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLusername))
                .addGroup(panelDriverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDriverLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(txtLpassword))
                    .addGroup(panelDriverLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("KELOLA KARYAWAN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(rbDriver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(txtHp, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(561, 561, 561)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(rbKasir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(panelDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(686, 686, 686)
                        .addComponent(btnPerbarui))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(txtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(rbDriver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(btnKembali))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(txtHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(btnSimpan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(rbKasir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(panelDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(btnPerbarui))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel6)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try{
            if(rbKasir.isSelected()){
                if(!validate(txtEmail.getText())){
                    JOptionPane.showMessageDialog(this, "Format email tidak tepat!");
                    return;
                }
                if(txtAlamat.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Alamat tidak boleh kosong!");
                    return;
                }
                if(txtHp.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "No HP tidak boleh kosong!");
                    return;
                }
                if(txtNama.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!");
                    return;
                }
                if(txtPassword.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Password tidak boleh kosong!");
                    return;
                }
                if(txtTgl.getDate().equals("")){
                    JOptionPane.showMessageDialog(this, "Tanggal lahir tidak benar!");
                    return;
                }
                if(txtUsername.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Username tidak boleh kosong!");
                    return;
                }
                if(txtNama.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!");
                    return;
                }
            }else{
                if(!validate(txtEmail.getText())){
                    JOptionPane.showMessageDialog(this, "Format email tidak tepat!");
                    return;
                }
                if(txtAlamat.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Alamat tidak boleh kosong!");
                    return;
                }
                if(txtHp.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "No HP tidak boleh kosong!");
                    return;
                }
                if(txtNama.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!");
                    return;
                }
//                if(txtPassword.getText().equals("")){
//                    JOptionPane.showMessageDialog(this, "Password tidak boleh kosong!");
//                    return;
//                }
                if(txtTgl.getDate().equals("")){
                    JOptionPane.showMessageDialog(this, "Tanggal lahir tidak benar!");
                    return;
                }
//                if(txtUsername.getText().equals("")){
//                    JOptionPane.showMessageDialog(this, "Username tidak boleh kosong!");
//                    return;
//                }
                if(txtNama.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!");
                    return;
                }
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Isi data dengan benar!");
            return;
        }
        
        SimpleDateFormat formatDate = new SimpleDateFormat("yyyyMMdd");
        
        
        karyawan.setKry_id(formatDate.format(new Date())+controllerKaryawan.getLastID());
        karyawan.setKry_nama(txtNama.getText());
        karyawan.setKry_no_hp(txtHp.getText());
        karyawan.setKry_email(txtEmail.getText());
        
        String jabatan = "";
        if(rbDriver.isSelected()){
            jabatan = "Pengemudi";
            karyawan.setKry_username("-");
            karyawan.setKry_password("-");
        }else{
            jabatan = "Kasir";
            karyawan.setKry_username(txtUsername.getText());
            karyawan.setKry_password(txtPassword.getText());
        }
        karyawan.setKry_jabatan(jabatan);
        
        karyawan.setKry_tgl_lahir(txtTgl.getDate());
        karyawan.setKry_total_transaksi("0");
        
        karyawan.setAlamat(txtAlamat.getText());
        try{
            controllerKaryawan.simpanKaryawan(karyawan);
            JOptionPane.showMessageDialog(this, "Tersimpan");
        }catch(Exception ex){
        }
        
        
        addData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tableKaryawanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKaryawanKeyPressed
        // TODO add your handling code here:
//        int i = tableKaryawan.getSelectedRow();
//        if (i == -1) {
//            return;
//        }
//            
//        txtNama.setText((String) model.getValueAt(i, 1));
//        txtHp.setText((String) model.getValueAt(i, 2));
//        txtEmail.setText((String) model.getValueAt(i, 3));
//        txtAlamat.setText((String) model.getValueAt(i, 5));
//        String dateValue = model.getValueAt(i, 4).toString();
//        
//        try {
//            java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
//            txtTgl.setDate(date);
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(this,
//                        "Masukkan data dengan benar!");
//        }
//        
//        if(((String) model.getValueAt(i, 6)).equals("Kasir")){
//            rbKasir.setSelected(true);
//            panelDriver.setEnabled(true);
//            txtUsername.setText((String) model.getValueAt(i, 8));
//            txtPassword.setText((String) model.getValueAt(i, 9));
//        }else{
//            rbDriver.setSelected(true);
//            panelDriver.setEnabled(false);
//        }
//        
    }//GEN-LAST:event_tableKaryawanKeyPressed

    private void tableKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKaryawanMouseClicked
        // TODO add your handling code here:
        karyawan = controllerTable.getSelectedRowKaryawan(tableKaryawan);
        txtNama.setText(karyawan.getKry_nama());
        txtHp.setText(karyawan.getKry_no_hp());
        txtAlamat.setText(karyawan.getAlamat());
        txtEmail.setText(karyawan.getKry_email());
        txtPassword.setText(karyawan.getKry_password());
        txtUsername.setText(karyawan.getKry_username());
        txtTgl.setDate(karyawan.getKry_tgl_lahir());
        System.out.println(karyawan.getKry_jabatan());
        
        if(karyawan.getKry_jabatan().equals("Kasir")){
            rbKasir.setSelected(true);
            rbKasir.setEnabled(true);
            rbDriver.setEnabled(true);
        }else if(karyawan.getKry_jabatan().equals("Manager")){
            rbKasir.setSelected(false);
            rbDriver.setSelected(false);
            rbKasir.setEnabled(false);
            rbDriver.setEnabled(false);
            
        }
        else{
            rbKasir.setEnabled(true);
            rbDriver.setEnabled(true);
            rbDriver.setSelected(true);
        }
    }//GEN-LAST:event_tableKaryawanMouseClicked

    private void btnPerbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerbaruiActionPerformed
        // TODO add your handling code here:
        try{
            if(rbKasir.isSelected()){
                if(!validate(txtEmail.getText())){
                    JOptionPane.showMessageDialog(this, "Format email tidak tepat!");
                    return;
                }
                if(txtAlamat.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Alamat tidak boleh kosong!");
                    return;
                }
                if(txtHp.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "No HP tidak boleh kosong!");
                    return;
                }
                if(txtNama.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!");
                    return;
                }
//                if(txtPassword.getText().equals("")){
//                    JOptionPane.showMessageDialog(this, "Password tidak boleh kosong!");
//                    return;
//                }
                if(txtTgl.getDate().equals("")){
                    JOptionPane.showMessageDialog(this, "Tanggal lahir tidak benar!");
                    return;
                }
                if(txtUsername.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Username tidak boleh kosong!");
                    return;
                }
                if(txtNama.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!");
                    return;
                }
            }else{
                if(!validate(txtEmail.getText())){
                    JOptionPane.showMessageDialog(this, "Format email tidak tepat!");
                    return;
                }
                if(txtAlamat.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Alamat tidak boleh kosong!");
                    return;
                }
                if(txtHp.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "No HP tidak boleh kosong!");
                    return;
                }
                if(txtNama.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!");
                    return;
                }
//                if(txtPassword.getText().equals("")){
//                    JOptionPane.showMessageDialog(this, "Password tidak boleh kosong!");
//                    return;
//                }
                if(txtTgl.getDate().equals("")){
                    JOptionPane.showMessageDialog(this, "Tanggal lahir tidak benar!");
                    return;
                }
//                if(txtUsername.getText().equals("")){
//                    JOptionPane.showMessageDialog(this, "Username tidak boleh kosong!");
//                    return;
//                }
                if(txtNama.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!");
                    return;
                }
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Isi data dengan benar!");
            return;
        }
        karyawan.setKry_nama(txtNama.getText());
        karyawan.setKry_no_hp(txtHp.getText());
        karyawan.setKry_email(txtEmail.getText());
        
        String jabatan = "";
        if(!rbDriver.isEnabled()){
            jabatan = "Manager";
            karyawan.setKry_username(txtUsername.getText());
            karyawan.setKry_password(txtPassword.getText());
        }else{
            if(rbDriver.isSelected()){
                jabatan = "Pengemudi";
                karyawan.setKry_username("-");
                karyawan.setKry_password("-");
            }
            else{
                jabatan = "Kasir";
                karyawan.setKry_username(txtUsername.getText());
                karyawan.setKry_password(txtPassword.getText());
            }
        }
        
        karyawan.setKry_jabatan(jabatan);
        
        karyawan.setKry_tgl_lahir(txtTgl.getDate());
        //karyawan.setKry_total_transaksi("0");
        
        karyawan.setAlamat(txtAlamat.getText());
        
        controllerKaryawan.updateKaryawan(karyawan);
        JOptionPane.showMessageDialog(this, "Berhasil memperbarui");
        addData();
    }//GEN-LAST:event_btnPerbaruiActionPerformed

    private void rbDriverStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbDriverStateChanged
        // TODO add your handling code here:
        if(rbDriver.isSelected()){
            txtLpassword.setEnabled(false);
            txtLusername.setEnabled(false);
            txtPassword.setEnabled(false);
            txtUsername.setEnabled(false);
        }else{
            txtLpassword.setEnabled(true);
            txtLusername.setEnabled(true);
            txtPassword.setEnabled(true);
            txtUsername.setEnabled(true);
        }
    }//GEN-LAST:event_rbDriverStateChanged

    private void txtNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNamaKeyPressed

    private void txtNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyTyped
        // TODO add your handling code here:
        if(txtNama.getText().length()==25){
            evt.consume();
        }else{
            char enter = evt.getKeyChar();
            if(!Character.isLetter(enter) && !Character.isISOControl(enter) && !Character.isWhitespace(enter)){
                evt.consume();
                
            }
        }
    }//GEN-LAST:event_txtNamaKeyTyped

    private void txtHpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHpKeyTyped
        // TODO add your handling code here:
        if(txtHp.getText().length()==13){
            evt.consume();
        }else{
            char enter = evt.getKeyChar();
            if(!Character.isDigit(enter) && !Character.isISOControl(enter)){
                evt.consume();
                
            }
        }
    }//GEN-LAST:event_txtHpKeyTyped

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        // TODO add your handling code here:
        if(txtEmail.getText().length()==30){
            evt.consume();
        }
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtAlamatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatKeyTyped
        // TODO add your handling code here:
        if(txtAlamat.getText().length()==100){
            evt.consume();
        }
    }//GEN-LAST:event_txtAlamatKeyTyped

    private void txtUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyTyped
        // TODO add your handling code here:
        if(txtUsername.getText().length()==25){
            evt.consume();
        }
    }//GEN-LAST:event_txtUsernameKeyTyped

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        // TODO add your handling code here:
        if(txtPassword.getText().length()==25){
            evt.consume();
        }
    }//GEN-LAST:event_txtPasswordKeyTyped

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnKembaliActionPerformed
    
    //Validasi Email
    public static final Pattern VALID_EMAIL_ADDRESS_REGEX = 
    Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);

    public static boolean validate(String emailStr) {
        Matcher matcher = VALID_EMAIL_ADDRESS_REGEX.matcher(emailStr);
        return matcher.find();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnPerbarui;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelDriver;
    private javax.swing.JRadioButton rbDriver;
    private javax.swing.JRadioButton rbKasir;
    private javax.swing.JTable tableKaryawan;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHp;
    private javax.swing.JLabel txtLpassword;
    private javax.swing.JLabel txtLusername;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPassword;
    private com.toedter.calendar.JDateChooser txtTgl;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
    
    
    public void resizeColumnWidth(JTable table) {
        final TableColumnModel columnModel = table.getColumnModel();
        for (int column = 0; column < table.getColumnCount(); column++) {
            int width = 15; // Min width
            for (int row = 0; row < table.getRowCount(); row++) {
                TableCellRenderer renderer = table.getCellRenderer(row, column);
                Component comp = table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width +1 , width);
            }
            if(width > 300)
                width=300;
            columnModel.getColumn(column).setPreferredWidth(width);
        }
    }
}
