/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi;

import Controller.CBarang;
import Controller.CPengiriman;
import Controller.CTableBarang;
import connection.DBConnect;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import sun.misc.Queue;

/**
 *
 * @author Polman
 */
public class TransaksiBarangKeluar extends javax.swing.JFrame {

    /**
     * Creates new form TransaksiBarangKeluar
     */
    //==========================DEKLARASI VARIABLE BARANG KELUAR =====================================
    private DefaultTableModel modelBarangKeluar = new DefaultTableModel();
    private DefaultTableModel modelDetailBarangKeluar = new DefaultTableModel();
    private DefaultTableModel modelKarungBarangKeluar = new DefaultTableModel();
    private DefaultTableModel modelDetailKarungBarangKeluar = new DefaultTableModel();

    CPengiriman ControllerPengirimanBarangKeluar = new CPengiriman();
    CTableBarang ControllerTabelBarangKeluar = new CTableBarang();

    List<String> detailKarungIndexBarangKeluar = new ArrayList<String>();
    List<String> detailKarungBarangBarangKeluar = new ArrayList<String>();
    List<String> detailKarungUkuranBarangKeluar = new ArrayList<String>();
    List<String> detailKarungKodiBarangKeluar = new ArrayList<String>();

    public TransaksiBarangKeluar() {
        initComponents();

        //======================= DEKLARASI BARANG MASUK =============================
        addColumnBarangKeluar();

        tableBarangKeluar.setModel(modelBarangKeluar);
        tableDetailBarangKeluar.setModel(modelDetailBarangKeluar);
        tableKarungPengirimanBarangKeluar.setModel(modelKarungBarangKeluar);
        tableDetailKarungPengirimanBarangKeluar.setModel(modelDetailKarungBarangKeluar);
        addComboBoxBarangKeluar();
        addDataBarangKeluar();
        btnTambahkanPengirimanBarangKeluar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelDaftarBarangMasuk = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbStatusBarangKeluar = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBarangKeluar = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDetailBarangKeluar = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtJumlahKodiBarangKeluar = new javax.swing.JSpinner();
        btnTambahkanPengirimanBarangKeluar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtBarangBarangKeluar = new javax.swing.JTextField();
        txtUkuranBarangKeluar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cmbNamaPelangganBarangKeluar = new javax.swing.JComboBox<>();
        cbPengiriman = new javax.swing.JCheckBox();
        panelDataPengirimanBarangBarangKeluar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtIDPengirimanBarangKeluar = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableKarungPengirimanBarangKeluar = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtJumlahKodiPengirimanBarang = new javax.swing.JTextField();
        txtJumlahKarungPengirimanBarang = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtKeteranganKarungBarangKeluar = new javax.swing.JTextArea();
        txtBatasKeteranganBarangKeluar = new javax.swing.JLabel();
        dummy1 = new javax.swing.JLabel();
        txtBatasKeteranganBarangKeluar1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableDetailKarungPengirimanBarangKeluar = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        txtNomorKarungBarangKeluar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelDaftarBarangMasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("DAFTAR BARANG KELUAR");

        cmbStatusBarangKeluar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disiapkan", "Selesai", "Batal" }));
        cmbStatusBarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusBarangKeluarActionPerformed(evt);
            }
        });

        jLabel1.setText("Status");

        tableBarangKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBarangKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBarangKeluarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBarangKeluar);

        tableDetailBarangKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableDetailBarangKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDetailBarangKeluarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableDetailBarangKeluar);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("DAFTAR DETAIL BARANG KELUAR");

        jLabel2.setText("JUMLAH KODI");

        txtJumlahKodiBarangKeluar.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        txtJumlahKodiBarangKeluar.setEditor(new javax.swing.JSpinner.NumberEditor(txtJumlahKodiBarangKeluar, ""));
        txtJumlahKodiBarangKeluar.setEnabled(false);

        btnTambahkanPengirimanBarangKeluar.setText("TAMBAHKAN KE PENGIRIMAN");
        btnTambahkanPengirimanBarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahkanPengirimanBarangKeluarActionPerformed(evt);
            }
        });

        jLabel10.setText("BARANG");

        txtBarangBarangKeluar.setText("[ NAMA BARANG ] ");
        txtBarangBarangKeluar.setEnabled(false);

        txtUkuranBarangKeluar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUkuranBarangKeluar.setText("[ UKURAN ]");
        txtUkuranBarangKeluar.setEnabled(false);

        jLabel16.setText("Pelanggan");

        cmbNamaPelangganBarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNamaPelangganBarangKeluarActionPerformed(evt);
            }
        });

        cbPengiriman.setText("Lakukan Pengiriman");
        cbPengiriman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPengirimanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDaftarBarangMasukLayout = new javax.swing.GroupLayout(panelDaftarBarangMasuk);
        panelDaftarBarangMasuk.setLayout(panelDaftarBarangMasukLayout);
        panelDaftarBarangMasukLayout.setHorizontalGroup(
            panelDaftarBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarBarangMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDaftarBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDaftarBarangMasukLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1078, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDaftarBarangMasukLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBarangBarangKeluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUkuranBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtJumlahKodiBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTambahkanPengirimanBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDaftarBarangMasukLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbPengiriman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbStatusBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbNamaPelangganBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelDaftarBarangMasukLayout.setVerticalGroup(
            panelDaftarBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarBarangMasukLayout.createSequentialGroup()
                .addGroup(panelDaftarBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbStatusBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel16)
                    .addComponent(cmbNamaPelangganBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPengiriman))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelDaftarBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtJumlahKodiBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambahkanPengirimanBarangKeluar)
                    .addComponent(jLabel10)
                    .addComponent(txtBarangBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUkuranBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(149, 149, 149))
        );

        panelDataPengirimanBarangBarangKeluar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("DATA PENGIRIMAN BARANG");

        txtIDPengirimanBarangKeluar.setText("[ ID PENGIRIMAN ]");
        txtIDPengirimanBarangKeluar.setEnabled(false);

        tableKarungPengirimanBarangKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableKarungPengirimanBarangKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKarungPengirimanBarangKeluarMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableKarungPengirimanBarangKeluar);

        jLabel3.setText("JUMLAH KODI");

        jLabel4.setText("JUMLAH KARUNG");

        txtJumlahKodiPengirimanBarang.setText("[ JUMLAH KODI ]");

        txtJumlahKarungPengirimanBarang.setText("[ JUMLAH KARUNG ]");

        jLabel14.setText("KARUNG PENGIRIMAN  ");

        javax.swing.GroupLayout panelDataPengirimanBarangBarangKeluarLayout = new javax.swing.GroupLayout(panelDataPengirimanBarangBarangKeluar);
        panelDataPengirimanBarangBarangKeluar.setLayout(panelDataPengirimanBarangBarangKeluarLayout);
        panelDataPengirimanBarangBarangKeluarLayout.setHorizontalGroup(
            panelDataPengirimanBarangBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataPengirimanBarangBarangKeluarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDataPengirimanBarangBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelDataPengirimanBarangBarangKeluarLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDPengirimanBarangKeluar))
                    .addGroup(panelDataPengirimanBarangBarangKeluarLayout.createSequentialGroup()
                        .addGroup(panelDataPengirimanBarangBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDataPengirimanBarangBarangKeluarLayout.createSequentialGroup()
                                .addGroup(panelDataPengirimanBarangBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtJumlahKodiPengirimanBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelDataPengirimanBarangBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtJumlahKarungPengirimanBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDataPengirimanBarangBarangKeluarLayout.setVerticalGroup(
            panelDataPengirimanBarangBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataPengirimanBarangBarangKeluarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDataPengirimanBarangBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtIDPengirimanBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataPengirimanBarangBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataPengirimanBarangBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJumlahKodiPengirimanBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJumlahKarungPengirimanBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setText("KETERANGAN KARUNG");

        txtKeteranganKarungBarangKeluar.setColumns(20);
        txtKeteranganKarungBarangKeluar.setLineWrap(true);
        txtKeteranganKarungBarangKeluar.setRows(5);
        txtKeteranganKarungBarangKeluar.setText("TULIS KETERANGAN KARUNG DI SINI");
        txtKeteranganKarungBarangKeluar.setAutoscrolls(false);
        txtKeteranganKarungBarangKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtKeteranganKarungBarangKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKeteranganKarungBarangKeluarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKeteranganKarungBarangKeluarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKeteranganKarungBarangKeluarKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(txtKeteranganKarungBarangKeluar);

        txtBatasKeteranganBarangKeluar.setText("0");

        dummy1.setText("/");

        txtBatasKeteranganBarangKeluar1.setText("50");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txtBatasKeteranganBarangKeluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dummy1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBatasKeteranganBarangKeluar1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtBatasKeteranganBarangKeluar)
                    .addComponent(dummy1)
                    .addComponent(txtBatasKeteranganBarangKeluar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText("TULIS KETERANGAN");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableDetailKarungPengirimanBarangKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableDetailKarungPengirimanBarangKeluar.setEnabled(false);
        tableDetailKarungPengirimanBarangKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDetailKarungPengirimanBarangKeluarMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tableDetailKarungPengirimanBarangKeluar);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setText("DETAIL KARUNG");

        txtNomorKarungBarangKeluar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNomorKarungBarangKeluar.setText("[ NO KARUNG ]");
        txtNomorKarungBarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomorKarungBarangKeluarActionPerformed(evt);
            }
        });
        txtNomorKarungBarangKeluar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtNomorKarungBarangKeluarPropertyChange(evt);
            }
        });

        jLabel5.setText("Nomor Karung");

        jLabel6.setText("AKSI");

        jButton3.setText("BATALKAN KARUNG");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ISI KETERANGAN DI SAMPING");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 312, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtNomorKarungBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addGap(279, 279, 279))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomorKarungBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jButton4.setText("KONFIRMASI PEMBERANGKATAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelDataPengirimanBarangBarangKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)))
                    .addComponent(panelDaftarBarangMasuk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDaftarBarangMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDataPengirimanBarangBarangKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void addComboBoxBarangKeluar() {
        try {
            DBConnect connection = new DBConnect();
            connection.stat = connection.conn.createStatement();
            String query = "select * from Pelanggan";
            connection.result = connection.stat.executeQuery(query);

            while (connection.result.next()) {

                cmbNamaPelangganBarangKeluar.addItem(connection.result.getString("pgn_nama"));
            }
            connection.stat.close();
            connection.result.close();
        } catch (Exception e) {
            System.out.println("Gagal111 addDataPemasok!\n" + e.toString());
        }
    }

    private void addColumnBarangKeluar() {
        modelBarangKeluar.addColumn("No");
        modelBarangKeluar.addColumn("Kode");
        modelBarangKeluar.addColumn("Pelanggan nama");
        modelBarangKeluar.addColumn("Pelanggan toko");
        modelBarangKeluar.addColumn("Pasar");
        modelBarangKeluar.addColumn("Tanggal transaksi");
        modelBarangKeluar.addColumn("Jumlah kodi");
        modelBarangKeluar.addColumn("Harga");
        modelBarangKeluar.addColumn("Status");

        modelDetailBarangKeluar.addColumn("No");
        modelDetailBarangKeluar.addColumn("Barang");
        modelDetailBarangKeluar.addColumn("Ukuran");
        modelDetailBarangKeluar.addColumn("Jumlah kodi");
        modelDetailBarangKeluar.addColumn("Harga");

        modelKarungBarangKeluar.addColumn("No");
        modelKarungBarangKeluar.addColumn("Kode");
        modelKarungBarangKeluar.addColumn("Keterangan");
        modelKarungBarangKeluar.addColumn("Kodi");
        modelKarungBarangKeluar.addColumn("Jenis");

        modelDetailKarungBarangKeluar.addColumn("No");
        modelDetailKarungBarangKeluar.addColumn("Barang");
        modelDetailKarungBarangKeluar.addColumn("Ukuran");
        modelDetailKarungBarangKeluar.addColumn("Kodi");
    }

    private void showDetailKarungBarangKeluar(String index) {

        modelDetailKarungBarangKeluar.getDataVector().removeAllElements();
        modelDetailKarungBarangKeluar.fireTableDataChanged();
        //JOptionPane.showMessageDialog(this, detailKarungIndexBarangKeluar.size());
        int baris = 1;
        for (int i = 0; i < detailKarungIndexBarangKeluar.size(); i++) {
            //JOptionPane.showMessageDialog(this, "ukuran index : " + detailKarungIndexBarangKeluar.size());
            if (detailKarungIndexBarangKeluar.get(i).toString().equals((index))) {
                Object[] dataRow = {baris, detailKarungBarangBarangKeluar.get(i), detailKarungUkuranBarangKeluar.get(i), detailKarungKodiBarangKeluar.get(i)};

                modelDetailKarungBarangKeluar.addRow(dataRow);
                baris++;
            }
        }
    }
    private void isiJumlahDetailKarungTransaksiBarangKeluar(){
        int nomorkarung = 1;
        int jumlah = 0;
        for(int i = 0; i < detailKarungIndexBarangKeluar.size(); i++){
            //JOptionPane.showMessageDialog(this, "Nomor karung : "+nomorkarung+"\nIndex karung detail : "+detailKarungIndexBarangKeluar.get(i));
//            JOptionPane.showMessageDialog(this, );
            if(nomorkarung == Integer.parseInt(detailKarungIndexBarangKeluar.get(i))){
                jumlah++;
            }
            else if(nomorkarung != Integer.parseInt(detailKarungIndexBarangKeluar.get(i)))
            {
                tableKarungPengirimanBarangKeluar.setValueAt(jumlah, nomorkarung-1, 4);
                jumlah = 1;
                nomorkarung++;
            }
            
            if(i+1==detailKarungIndexBarangKeluar.size()){
                tableKarungPengirimanBarangKeluar.setValueAt(jumlah, nomorkarung-1, 4);
            }
        }
    }
    private void addDataBarangKeluar() {

        modelBarangKeluar.getDataVector().removeAllElements();

        modelBarangKeluar.fireTableDataChanged();
        ControllerTabelBarangKeluar.addDataBarangKeluar(modelBarangKeluar, (String) cmbStatusBarangKeluar.getSelectedItem(), (String) cmbNamaPelangganBarangKeluar.getSelectedItem());
    }
    private void cmbStatusBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusBarangKeluarActionPerformed
        // TODO add your handling code here:
        modelBarangKeluar.getDataVector().removeAllElements();

        modelBarangKeluar.fireTableDataChanged();
        ControllerTabelBarangKeluar.addDataBarangKeluar(modelBarangKeluar, (String) cmbStatusBarangKeluar.getSelectedItem(), (String) cmbNamaPelangganBarangKeluar.getSelectedItem());
    }//GEN-LAST:event_cmbStatusBarangKeluarActionPerformed
    private void tableBarangKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBarangKeluarMouseClicked
        // TODO add your handling code here:
        perbaruiDetailBarangKeluar();
    }//GEN-LAST:event_tableBarangKeluarMouseClicked
    private void perbaruiDetailBarangKeluar() {
        modelDetailBarangKeluar.getDataVector().removeAllElements();

        modelDetailBarangKeluar.fireTableDataChanged();
        ControllerTabelBarangKeluar.addDataDetailBarangKeluar(modelDetailBarangKeluar, (String) tableBarangKeluar.getValueAt(tableBarangKeluar.getSelectedRow(), 1));
    }
    private void tableDetailBarangKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDetailBarangKeluarMouseClicked
        // TODO add your handling code here:
        try {
            txtBarangBarangKeluar.setText(tableDetailBarangKeluar.getValueAt(tableDetailBarangKeluar.getSelectedRow(), 1).toString());
            txtUkuranBarangKeluar.setText(tableDetailBarangKeluar.getValueAt(tableDetailBarangKeluar.getSelectedRow(), 2).toString());
            txtJumlahKodiBarangKeluar.setValue(Integer.parseInt((String) tableDetailBarangKeluar.getValueAt(tableDetailBarangKeluar.getSelectedRow(), 3)));
        } catch (Exception ex) {

        }

    }//GEN-LAST:event_tableDetailBarangKeluarMouseClicked
    private void tableKarungPengirimanBarangKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKarungPengirimanBarangKeluarMouseClicked
        // TODO add your handling code here:
        txtNomorKarungBarangKeluar.setText(Integer.toString(tableKarungPengirimanBarangKeluar.getSelectedRow() + 1));
        showDetailKarungBarangKeluar(txtNomorKarungBarangKeluar.getText());
    }//GEN-LAST:event_tableKarungPengirimanBarangKeluarMouseClicked
    private void txtKeteranganKarungBarangKeluarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeteranganKarungBarangKeluarKeyReleased
        // TODO add your handling code here:
        txtBatasKeteranganBarangKeluar.setText(Integer.toString(txtKeteranganKarungBarangKeluar.getText().length()));
    }//GEN-LAST:event_txtKeteranganKarungBarangKeluarKeyReleased
    private void txtKeteranganKarungBarangKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeteranganKarungBarangKeluarKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtKeteranganKarungBarangKeluarKeyPressed
    private void txtKeteranganKarungBarangKeluarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeteranganKarungBarangKeluarKeyTyped
        // TODO add your handling code here:
        txtBatasKeteranganBarangKeluar.setText(Integer.toString(txtKeteranganKarungBarangKeluar.getText().length()));
        if (txtKeteranganKarungBarangKeluar.getText().length() == 50) {
            evt.consume();
        }
    }//GEN-LAST:event_txtKeteranganKarungBarangKeluarKeyTyped
    private void tableDetailKarungPengirimanBarangKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDetailKarungPengirimanBarangKeluarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableDetailKarungPengirimanBarangKeluarMouseClicked
    private void cmbNamaPelangganBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNamaPelangganBarangKeluarActionPerformed
        // TODO add your handling code here:
        modelBarangKeluar.getDataVector().removeAllElements();

        modelBarangKeluar.fireTableDataChanged();
        ControllerTabelBarangKeluar.addDataBarangKeluar(modelBarangKeluar, (String) cmbStatusBarangKeluar.getSelectedItem(), (String) cmbNamaPelangganBarangKeluar.getSelectedItem());
    }//GEN-LAST:event_cmbNamaPelangganBarangKeluarActionPerformed
    private void cbPengirimanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPengirimanActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formatter = new SimpleDateFormat("yyyyMMdd");
        if (cbPengiriman.isSelected()) {
            btnTambahkanPengirimanBarangKeluar.setEnabled(true);
            txtIDPengirimanBarangKeluar.setText(formatter.format(new Date()) + "-" + ControllerPengirimanBarangKeluar.getLastID());
        } else {
            btnTambahkanPengirimanBarangKeluar.setEnabled(false);
            txtIDPengirimanBarangKeluar.setText("[ ID PENGIRIMAN ]");
        }
    }//GEN-LAST:event_cbPengirimanActionPerformed

    private void btnTambahkanPengirimanBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahkanPengirimanBarangKeluarActionPerformed
        // TODO add your handling code here:
        if (tableDetailBarangKeluar.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Tidak ada data terpilih! ");
            return;
        }
        int kode = 64;
        
        // jika kosong
        //       masukkan data semua
        //             jika semua data lebih dari 40
        //           masukkan 40 saja
        //                  sisanya masukkan ke karung berikutnya
        Object[] dataRowKarung = {"", "", "", "", ""};
        Object[] dataRowDetailKarung = {"", "", "", ""};
        if (tableKarungPengirimanBarangKeluar.getRowCount() == 0) {
            while ((int) txtJumlahKodiBarangKeluar.getValue() > 0) {
                if ((int) txtJumlahKodiBarangKeluar.getValue() >= 40) {
                    Object[] data = {tableKarungPengirimanBarangKeluar.getRowCount() + 1, txtIDPengirimanBarangKeluar.getText()+(char)(kode+(tableKarungPengirimanBarangKeluar.getRowCount() + 1)), "ISI DI SAMPING", "40", ""};

                    //System.out.println(i);
                    Object[] dataDetail = {"", txtBarangBarangKeluar.getText(), txtUkuranBarangKeluar.getText(), "40"};

                    detailKarungIndexBarangKeluar.add(Integer.toString(tableKarungPengirimanBarangKeluar.getRowCount() + 1));
                    detailKarungBarangBarangKeluar.add(txtBarangBarangKeluar.getText());
                    detailKarungUkuranBarangKeluar.add(txtUkuranBarangKeluar.getText());
                    detailKarungKodiBarangKeluar.add("40");

                    JOptionPane.showMessageDialog(this, Integer.toString(tableKarungPengirimanBarangKeluar.getRowCount() + 1));
                    dataRowDetailKarung = dataDetail;
                    dataRowKarung = data;

                    txtJumlahKodiBarangKeluar.setValue((int) txtJumlahKodiBarangKeluar.getValue() - 40);
                } else {
                    Object[] data = {tableKarungPengirimanBarangKeluar.getRowCount() + 1, txtIDPengirimanBarangKeluar.getText()+(char)(kode+tableKarungPengirimanBarangKeluar.getRowCount() + 1), "ISI DI SAMPING", txtJumlahKodiBarangKeluar.getValue(), ""};
                    Object[] dataDetail = {"", txtBarangBarangKeluar.getText(), txtUkuranBarangKeluar.getText(), txtJumlahKodiBarangKeluar.getValue()};

                    JOptionPane.showMessageDialog(this, "Masuk else");
                    detailKarungIndexBarangKeluar.add(Integer.toString(tableKarungPengirimanBarangKeluar.getRowCount() + 1));
                    detailKarungBarangBarangKeluar.add(txtBarangBarangKeluar.getText());
                    detailKarungUkuranBarangKeluar.add(txtUkuranBarangKeluar.getText());
                    detailKarungKodiBarangKeluar.add(txtJumlahKodiBarangKeluar.getValue().toString());

                    dataRowDetailKarung = dataDetail;
                    dataRowKarung = data;

                    txtJumlahKodiBarangKeluar.setValue(0);

                }
                modelKarungBarangKeluar.addRow(dataRowKarung);
                //modelDetailKarungBarangKeluar.addRow(dataRowDetailKarung);
            }
            isiJumlahDetailKarungTransaksiBarangKeluar();
        } else {
            // ELSE UNTUK ROW LEBIH DARI 1
            //  jikasudah ada 1 karung
            // periksa apakah sudah 40 isinya
            // jika sudah, buat karung baru
            //
            // jika belum , masukkan ke detil karung dan ubah jumlahnya
            // ubah tulisan jumlah kodi nya, dan masukkan detitlnya sesuai row paling bawah
            while ((int) txtJumlahKodiBarangKeluar.getValue() > 0) {
                if (Integer.parseInt(tableKarungPengirimanBarangKeluar.getValueAt((tableKarungPengirimanBarangKeluar.getRowCount() - 1), 3).toString()) == 40) {
                    if ((int) txtJumlahKodiBarangKeluar.getValue() >= 40) {
                        Object[] data = {tableKarungPengirimanBarangKeluar.getRowCount() + 1, txtIDPengirimanBarangKeluar.getText()+(char)(kode+tableKarungPengirimanBarangKeluar.getRowCount() + 1), "ISI DI SAMPING", "40", ""};

                        //System.out.println(i);
                        Object[] dataDetail = {"", txtBarangBarangKeluar.getText(), txtUkuranBarangKeluar.getText(), "40"};

                        detailKarungIndexBarangKeluar.add(Integer.toString(tableKarungPengirimanBarangKeluar.getRowCount() + 1));
                        detailKarungBarangBarangKeluar.add(txtBarangBarangKeluar.getText());
                        detailKarungUkuranBarangKeluar.add(txtUkuranBarangKeluar.getText());
                        detailKarungKodiBarangKeluar.add("40");

                        JOptionPane.showMessageDialog(this, Integer.toString(tableKarungPengirimanBarangKeluar.getRowCount() + 1));
                        dataRowDetailKarung = dataDetail;
                        dataRowKarung = data;

                        txtJumlahKodiBarangKeluar.setValue((int) txtJumlahKodiBarangKeluar.getValue() - 40);
                    } else {
                        Object[] data = {tableKarungPengirimanBarangKeluar.getRowCount() + 1, txtIDPengirimanBarangKeluar.getText()+(char)(kode+tableKarungPengirimanBarangKeluar.getRowCount() + 1), "ISI DI SAMPING", txtJumlahKodiBarangKeluar.getValue(), ""};
                        Object[] dataDetail = {"", txtBarangBarangKeluar.getText(), txtUkuranBarangKeluar.getText(), txtJumlahKodiBarangKeluar.getValue()};

                        JOptionPane.showMessageDialog(this, "Masuk else");
                        detailKarungIndexBarangKeluar.add(Integer.toString(tableKarungPengirimanBarangKeluar.getRowCount() + 1));
                        detailKarungBarangBarangKeluar.add(txtBarangBarangKeluar.getText());
                        detailKarungUkuranBarangKeluar.add(txtUkuranBarangKeluar.getText());
                        detailKarungKodiBarangKeluar.add(txtJumlahKodiBarangKeluar.getValue().toString());

                        dataRowDetailKarung = dataDetail;
                        dataRowKarung = data;

                        txtJumlahKodiBarangKeluar.setValue(0);

                    }
                    modelKarungBarangKeluar.addRow(dataRowKarung);
                    //modelDetailKarungBarangKeluar.addRow(dataRowDetailKarung);

                } else {
                    // jika blm 40
                    // periksa jumlah kodi nya
                    // jika lebih dari 40, masukkan hingga karung itu 40 -> tambahkan ke detil
                    // jika tidak lebih dari 40, masukkan hingga total 40 ->
                    // jika kurang ya masukkan saja semua ->
                    int disana = 0;
                    int jumlahsaya = Integer.parseInt(txtJumlahKodiBarangKeluar.getValue().toString());
                    int jumlahygada = Integer.parseInt(tableKarungPengirimanBarangKeluar.getValueAt(tableKarungPengirimanBarangKeluar.getRowCount() - 1, 3).toString());
                    int jumlahketerima = 0;
                    int daya = 40;
                    
                    int kebutuhan = daya - jumlahygada;
                    if(kebutuhan > jumlahsaya){
                        disana = jumlahygada + jumlahsaya;
                        jumlahketerima = jumlahsaya; 
                        jumlahsaya = 0;
                    }else if(jumlahsaya > kebutuhan){
                        disana = daya;
                        jumlahketerima = kebutuhan;
                        jumlahsaya = jumlahsaya - kebutuhan;
                    }
                    

                    tableKarungPengirimanBarangKeluar.setValueAt(Integer.toString(disana), tableKarungPengirimanBarangKeluar.getRowCount() - 1, 3);

                    JOptionPane.showMessageDialog(this, "Masuk sisa itu loh");
                    detailKarungIndexBarangKeluar.add(Integer.toString(tableKarungPengirimanBarangKeluar.getRowCount()));
                    detailKarungBarangBarangKeluar.add(txtBarangBarangKeluar.getText());
                    detailKarungUkuranBarangKeluar.add(txtUkuranBarangKeluar.getText());
                    detailKarungKodiBarangKeluar.add(Integer.toString(jumlahketerima));

                    txtJumlahKodiBarangKeluar.setValue(jumlahsaya);

                }
            }
            isiJumlahDetailKarungTransaksiBarangKeluar();
        }
        if (Integer.parseInt(tableDetailBarangKeluar.getValueAt(tableDetailBarangKeluar.getRowCount() - 1, 3).toString()) <= 40) {
            JOptionPane.showMessageDialog(this, "Bawah 40! ");
        }
        
        //modelDetailBarangKeluar
    }//GEN-LAST:event_btnTambahkanPengirimanBarangKeluarActionPerformed
    
    private void txtNomorKarungBarangKeluarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtNomorKarungBarangKeluarPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNomorKarungBarangKeluarPropertyChange

    private void txtNomorKarungBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomorKarungBarangKeluarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNomorKarungBarangKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiBarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiBarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiBarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiBarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiBarangKeluar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTambahkanPengirimanBarangKeluar;
    private javax.swing.JCheckBox cbPengiriman;
    private javax.swing.JComboBox<String> cmbNamaPelangganBarangKeluar;
    private javax.swing.JComboBox<String> cmbStatusBarangKeluar;
    private javax.swing.JLabel dummy1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel panelDaftarBarangMasuk;
    private javax.swing.JPanel panelDataPengirimanBarangBarangKeluar;
    private javax.swing.JTable tableBarangKeluar;
    private javax.swing.JTable tableDetailBarangKeluar;
    private javax.swing.JTable tableDetailKarungPengirimanBarangKeluar;
    private javax.swing.JTable tableKarungPengirimanBarangKeluar;
    private javax.swing.JTextField txtBarangBarangKeluar;
    private javax.swing.JLabel txtBatasKeteranganBarangKeluar;
    private javax.swing.JLabel txtBatasKeteranganBarangKeluar1;
    private javax.swing.JTextField txtIDPengirimanBarangKeluar;
    private javax.swing.JTextField txtJumlahKarungPengirimanBarang;
    private javax.swing.JSpinner txtJumlahKodiBarangKeluar;
    private javax.swing.JTextField txtJumlahKodiPengirimanBarang;
    private javax.swing.JTextArea txtKeteranganKarungBarangKeluar;
    private javax.swing.JTextField txtNomorKarungBarangKeluar;
    private javax.swing.JTextField txtUkuranBarangKeluar;
    // End of variables declaration//GEN-END:variables
}
