/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi;

import Controller.CBarang;
import Controller.CPemasokkan;
import Controller.CSupplier;
import Controller.CTableBarang;
import RTClass.Pemasok;
import java.awt.Component;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Polman
 */
public class TransaksiBarangMasuk extends javax.swing.JFrame {

    /**
     * Creates new form TransaksiBarangMasuk
     */
    //==========================DEKLARASI VARIABLE BARANG MASUK =====================================
    private DefaultTableModel modelBarangMasuk = new DefaultTableModel();
    private DefaultTableModel modelDetailBarangMasuk = new DefaultTableModel();
    CTableBarang ControllerTableBarangBarangMasuk = new CTableBarang();
    CSupplier ControllerPemasokBarangMasuk = new CSupplier();
    CPemasokkan ControllerPemasokkanBarangMasuk = new CPemasokkan();
    CBarang ControllerBarangBarangMasuk = new CBarang();

    Pemasok pemasok = new Pemasok();

    DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
    DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

    long sisaHutangBarangMasuk = 0;
    long calonSisaHutangBarangMasuk = 0;

    public TransaksiBarangMasuk() {

        initComponents();
        
        //======================= DEKLARASI BARANG MASUK =============================
        addColumnBarangMasuk();
        addDataBarangMasuk();
        tableBarangMasuk.setModel(modelBarangMasuk);
        tableDetailBarangMasuk.setModel(modelDetailBarangMasuk);
        //resizeColumnWidth(tableBarangMasuk);

        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(formatRp);

    }

    public void resizeColumnWidth(JTable table) {
        final TableColumnModel columnModel = table.getColumnModel();
        for (int column = 0; column < table.getColumnCount(); column++) {
            int width = 15; // Min width
            for (int row = 0; row < table.getRowCount(); row++) {
                TableCellRenderer renderer = table.getCellRenderer(row, column);
                Component comp = table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width + 1, width);
            }
            if (width > 300) {
                width = 300;
            }
            columnModel.getColumn(column).setPreferredWidth(width);
        }
    }

    private void addColumnBarangMasuk() {
        modelBarangMasuk.addColumn("No");
        modelBarangMasuk.addColumn("Kode Transaksi");
        modelBarangMasuk.addColumn("Pemasok");
        modelBarangMasuk.addColumn("Tanggal Transaksi");
        modelBarangMasuk.addColumn("Banyak Barang (Kodi)");
        modelBarangMasuk.addColumn("Harga");
        modelBarangMasuk.addColumn("Status");

        modelDetailBarangMasuk.addColumn("No");
        modelDetailBarangMasuk.addColumn("Barang");
        modelDetailBarangMasuk.addColumn("Ukuran");
        modelDetailBarangMasuk.addColumn("Banyak Barang (Kodi)");
        modelDetailBarangMasuk.addColumn("Harga");
    }

    private void addDataBarangMasuk() {

        modelBarangMasuk.getDataVector().removeAllElements();

        modelBarangMasuk.fireTableDataChanged();
        ControllerTableBarangBarangMasuk.addDataBarangMasuk(modelBarangMasuk, (String) cmbStatusBarangMasuk.getSelectedItem());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarangMasuk = new javax.swing.JPanel();
        panelDaftarBarangMasuk = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbStatusBarangMasuk = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBarangMasuk = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDetailBarangMasuk = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        panelDeskripsiBarangMasuk = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNamaPemasokBarangMasuk = new javax.swing.JTextField();
        txtJumlahTransaksiBarangMasuk = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUangTransaksiBarangMasuk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHutangBarangMasuk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtUangDibayarBarangMasuk = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSisaHutangBarangMasuk = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lblKeteranganBarangMasuk = new javax.swing.JLabel();
        btnSuksesBarangMasuk = new javax.swing.JButton();
        btnGagalBarangMasuk = new javax.swing.JButton();
        btnKonfirmasiBarangMasuk = new javax.swing.JButton();
        txtTagihanBarangMasuk = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1110, 660));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBarangMasuk.setMinimumSize(new java.awt.Dimension(1100, 652));
        panelBarangMasuk.setPreferredSize(new java.awt.Dimension(1100, 652));
        panelBarangMasuk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDaftarBarangMasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("DAFTAR BARANG MASUK");

        cmbStatusBarangMasuk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proses", "Sukses", "Gagal" }));
        cmbStatusBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusBarangMasukActionPerformed(evt);
            }
        });

        jLabel1.setText("Status");

        tableBarangMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBarangMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBarangMasukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBarangMasuk);

        tableDetailBarangMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableDetailBarangMasuk.setEnabled(false);
        tableDetailBarangMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDetailBarangMasukMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableDetailBarangMasuk);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("DETAIL DAFTAR BARANG MASUK");

        javax.swing.GroupLayout panelDaftarBarangMasukLayout = new javax.swing.GroupLayout(panelDaftarBarangMasuk);
        panelDaftarBarangMasuk.setLayout(panelDaftarBarangMasukLayout);
        panelDaftarBarangMasukLayout.setHorizontalGroup(
            panelDaftarBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarBarangMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDaftarBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDaftarBarangMasukLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1086, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelDaftarBarangMasukLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbStatusBarangMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDaftarBarangMasukLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(panelDaftarBarangMasukLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelDaftarBarangMasukLayout.setVerticalGroup(
            panelDaftarBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarBarangMasukLayout.createSequentialGroup()
                .addGroup(panelDaftarBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbStatusBarangMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        panelBarangMasuk.add(panelDaftarBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1100, 450));

        panelDeskripsiBarangMasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDeskripsiBarangMasuk.setPreferredSize(new java.awt.Dimension(1100, 185));
        panelDeskripsiBarangMasuk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("DESKRIPSI TRANSAKSI BARANG MASUK");
        panelDeskripsiBarangMasuk.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 287, 33));

        jLabel2.setText("Nama");
        panelDeskripsiBarangMasuk.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 50, 99, -1));

        txtNamaPemasokBarangMasuk.setText("-");
        panelDeskripsiBarangMasuk.add(txtNamaPemasokBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 46, 240, -1));

        txtJumlahTransaksiBarangMasuk.setText("-");
        panelDeskripsiBarangMasuk.add(txtJumlahTransaksiBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 82, 240, -1));

        jLabel3.setText("Jumlah transaksi");
        panelDeskripsiBarangMasuk.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 86, -1, -1));

        txtUangTransaksiBarangMasuk.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtUangTransaksiBarangMasuk.setText("Rp. 0,00");
        panelDeskripsiBarangMasuk.add(txtUangTransaksiBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 118, 240, -1));

        jLabel4.setText("Uang transaksi");
        panelDeskripsiBarangMasuk.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 122, 99, -1));

        jLabel5.setText("Hutang");
        panelDeskripsiBarangMasuk.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 154, 99, -1));

        txtHutangBarangMasuk.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHutangBarangMasuk.setText("Rp. 0,00");
        panelDeskripsiBarangMasuk.add(txtHutangBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 154, 240, -1));

        jLabel6.setText("Banyak uang dibayar");
        panelDeskripsiBarangMasuk.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 83, -1, -1));

        txtUangDibayarBarangMasuk.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtUangDibayarBarangMasuk.setText("0");
        txtUangDibayarBarangMasuk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUangDibayarBarangMasukKeyReleased(evt);
            }
        });
        panelDeskripsiBarangMasuk.add(txtUangDibayarBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 105, 179, -1));

        jLabel9.setText("Rp");
        panelDeskripsiBarangMasuk.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 109, -1, -1));

        jLabel10.setText("Sisa hutang pada pemasok");
        panelDeskripsiBarangMasuk.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 135, -1, -1));

        txtSisaHutangBarangMasuk.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSisaHutangBarangMasuk.setText("Rp. 0,00");
        panelDeskripsiBarangMasuk.add(txtSisaHutangBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 157, 200, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("KETERANGAN TRANSAKSI BARANG MASUK");
        panelDeskripsiBarangMasuk.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 7, -1, -1));

        lblKeteranganBarangMasuk.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblKeteranganBarangMasuk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeteranganBarangMasuk.setText("[Keterangan]");
        lblKeteranganBarangMasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDeskripsiBarangMasuk.add(lblKeteranganBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 32, 428, 55));

        btnSuksesBarangMasuk.setText("Sukses");
        btnSuksesBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuksesBarangMasukActionPerformed(evt);
            }
        });
        panelDeskripsiBarangMasuk.add(btnSuksesBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 93, 209, -1));

        btnGagalBarangMasuk.setText("Gagal");
        btnGagalBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGagalBarangMasukActionPerformed(evt);
            }
        });
        panelDeskripsiBarangMasuk.add(btnGagalBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 93, 209, -1));

        btnKonfirmasiBarangMasuk.setText("Konfirmasi");
        btnKonfirmasiBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmasiBarangMasukActionPerformed(evt);
            }
        });
        panelDeskripsiBarangMasuk.add(btnKonfirmasiBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(663, 131, 430, -1));

        txtTagihanBarangMasuk.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTagihanBarangMasuk.setText("Rp. 0,00");
        panelDeskripsiBarangMasuk.add(txtTagihanBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 50, 200, -1));

        jLabel14.setText("Tagihan");
        panelDeskripsiBarangMasuk.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        panelBarangMasuk.add(panelDeskripsiBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 460, 1100, 190));

        getContentPane().add(panelBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbStatusBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusBarangMasukActionPerformed
        // TODO add your handling code here:
        clear();
        modelDetailBarangMasuk.getDataVector().removeAllElements();
        modelDetailBarangMasuk.fireTableDataChanged();

        modelBarangMasuk.getDataVector().removeAllElements();
        modelBarangMasuk.fireTableDataChanged();
        ControllerTableBarangBarangMasuk.addDataBarangMasuk(modelBarangMasuk, (String) cmbStatusBarangMasuk.getSelectedItem());
    }//GEN-LAST:event_cmbStatusBarangMasukActionPerformed

    private void perbaruiDetail() {
        modelDetailBarangMasuk.getDataVector().removeAllElements();

        modelDetailBarangMasuk.fireTableDataChanged();
        ControllerTableBarangBarangMasuk.addDataDetailBarangMasuk(modelDetailBarangMasuk, (String) tableBarangMasuk.getValueAt(tableBarangMasuk.getSelectedRow(), 1));
    }
    private void tableBarangMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBarangMasukMouseClicked
        // TODO add your handling code here:
        if (!cmbStatusBarangMasuk.getSelectedItem().toString().equals("Proses")) {
            btnKonfirmasiBarangMasuk.setEnabled(false);
        } else {
            btnKonfirmasiBarangMasuk.setEnabled(true);
        }

        pemasok = ControllerPemasokBarangMasuk.getDataPemasok(tableBarangMasuk.getValueAt(tableBarangMasuk.getSelectedRow(), 2).toString());
        perbaruiDetail();
        txtNamaPemasokBarangMasuk.setText(pemasok.getPms_nama());
        txtJumlahTransaksiBarangMasuk.setText(Integer.toString(pemasok.getPms_jumlah_transaksi()));
        txtUangTransaksiBarangMasuk.setText(kursIndonesia.format(pemasok.getPms_uang_transaksi()));
        txtHutangBarangMasuk.setText(kursIndonesia.format(pemasok.getPms_total_hutang()));

        if (!cmbStatusBarangMasuk.getSelectedItem().toString().equals("Proses")) {
            btnKonfirmasiBarangMasuk.setEnabled(false);
            txtSisaHutangBarangMasuk.setText(kursIndonesia.format(0));
            txtTagihanBarangMasuk.setText(kursIndonesia.format(0));
            txtUangDibayarBarangMasuk.setText("0");

            txtSisaHutangBarangMasuk.setEnabled(false);
            txtTagihanBarangMasuk.setEnabled(false);
            txtUangDibayarBarangMasuk.setEnabled(false);
        } else {
            txtSisaHutangBarangMasuk.setEnabled(true);
            txtTagihanBarangMasuk.setEnabled(true);
            txtUangDibayarBarangMasuk.setEnabled(true);
            btnKonfirmasiBarangMasuk.setEnabled(true);
            txtSisaHutangBarangMasuk.setText(kursIndonesia.format(pemasok.getPms_total_hutang()));
            txtTagihanBarangMasuk.setText(tableBarangMasuk.getValueAt(tableBarangMasuk.getSelectedRow(), 5).toString());

            try {
                // a = tagihan
                // b = bayar
                // c = total hutang
                // d = calon sisa hutang
                // d = (a+c)-d
                txtSisaHutangBarangMasuk.setText(kursIndonesia.format(((long) kursIndonesia.parse(txtTagihanBarangMasuk.getText()) + (long) kursIndonesia.parse(txtHutangBarangMasuk.getText())) - Long.parseLong(txtUangDibayarBarangMasuk.getText())));
            } catch (Exception ex) {

            }
        }

    }//GEN-LAST:event_tableBarangMasukMouseClicked

    private void btnSuksesBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuksesBarangMasukActionPerformed
        // TODO add your handling code here:
        txtUangDibayarBarangMasuk.setEnabled(true);
        lblKeteranganBarangMasuk.setText("Sukses");
    }//GEN-LAST:event_btnSuksesBarangMasukActionPerformed

    private void btnGagalBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGagalBarangMasukActionPerformed
        // TODO add your handling code here:
        txtUangDibayarBarangMasuk.setText("0");
        try {
            // a = tagihan
            // b = bayar
            // c = total hutang
            // d = calon sisa hutang
            // d = (a+c)-d
            txtSisaHutangBarangMasuk.setText(kursIndonesia.format(((long) kursIndonesia.parse(txtTagihanBarangMasuk.getText()) + (long) kursIndonesia.parse(txtHutangBarangMasuk.getText())) - Long.parseLong(txtUangDibayarBarangMasuk.getText())));
        } catch (Exception ex) {

        }
        lblKeteranganBarangMasuk.setText("Gagal");
        txtUangDibayarBarangMasuk.setEnabled(false);
    }//GEN-LAST:event_btnGagalBarangMasukActionPerformed

    private void btnKonfirmasiBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiBarangMasukActionPerformed
        // TODO add your handling code here:
        if (lblKeteranganBarangMasuk.getText().equals("[Keterangan]")) {
            JOptionPane.showMessageDialog(this, "Belum pilih status");
            return;
        }   

        try {
            if (lblKeteranganBarangMasuk.getText().equals("Sukses")) {
                ControllerPemasokBarangMasuk.updateTransaksiPemasokkan(Long.parseLong(txtUangDibayarBarangMasuk.getText()), Long.parseLong((kursIndonesia.parse(txtSisaHutangBarangMasuk.getText())).toString()), pemasok.getPms_id().toString());
                for (int i = 0; i < tableDetailBarangMasuk.getRowCount(); i++) {
                ControllerBarangBarangMasuk.updateJumlahBarang(tableDetailBarangMasuk.getValueAt(i, 3).toString(),tableDetailBarangMasuk.getValueAt(i, 1).toString(),tableDetailBarangMasuk.getValueAt(i, 2).toString());
                }
            }
            ControllerPemasokkanBarangMasuk.updateStatusPemasokkan(lblKeteranganBarangMasuk.getText(), (String) tableBarangMasuk.getValueAt(tableBarangMasuk.getSelectedRow(), 1));
            

            addDataBarangMasuk();
            JOptionPane.showMessageDialog(this, "Transaksi berhasil dilaksanakan!");
            clear();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Tidak dapat menyimpan!");
        }

    }//GEN-LAST:event_btnKonfirmasiBarangMasukActionPerformed
    private void clear() {

        txtNamaPemasokBarangMasuk.setText("-");
        txtJumlahTransaksiBarangMasuk.setText("0");
        txtUangTransaksiBarangMasuk.setText(kursIndonesia.format(0));
        txtHutangBarangMasuk.setText(kursIndonesia.format(0));

        txtSisaHutangBarangMasuk.setText(kursIndonesia.format(0));
        txtTagihanBarangMasuk.setText(kursIndonesia.format(0));
        txtUangDibayarBarangMasuk.setText("0");

    }
    private void txtUangDibayarBarangMasukKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUangDibayarBarangMasukKeyReleased
        // TODO add your handling code here:
        if (txtUangDibayarBarangMasuk.getText().equals("")) {
            txtSisaHutangBarangMasuk.setText(txtHutangBarangMasuk.getText());
            return;
        }

        try {
            // a = tagihan
            // b = bayar
            // c = total hutang
            // d = calon sisa hutang
            // d = (a+c)-d
            txtSisaHutangBarangMasuk.setText(kursIndonesia.format(((long) kursIndonesia.parse(txtTagihanBarangMasuk.getText()) + (long) kursIndonesia.parse(txtHutangBarangMasuk.getText())) - Long.parseLong(txtUangDibayarBarangMasuk.getText())));
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_txtUangDibayarBarangMasukKeyReleased

    private void tableDetailBarangMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDetailBarangMasukMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableDetailBarangMasukMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiBarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiBarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiBarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiBarangMasuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiBarangMasuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGagalBarangMasuk;
    private javax.swing.JButton btnKonfirmasiBarangMasuk;
    private javax.swing.JButton btnSuksesBarangMasuk;
    private javax.swing.JComboBox<String> cmbStatusBarangMasuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblKeteranganBarangMasuk;
    private javax.swing.JPanel panelBarangMasuk;
    private javax.swing.JPanel panelDaftarBarangMasuk;
    private javax.swing.JPanel panelDeskripsiBarangMasuk;
    private javax.swing.JTable tableBarangMasuk;
    private javax.swing.JTable tableDetailBarangMasuk;
    private javax.swing.JTextField txtHutangBarangMasuk;
    private javax.swing.JTextField txtJumlahTransaksiBarangMasuk;
    private javax.swing.JTextField txtNamaPemasokBarangMasuk;
    private javax.swing.JTextField txtSisaHutangBarangMasuk;
    private javax.swing.JTextField txtTagihanBarangMasuk;
    private javax.swing.JTextField txtUangDibayarBarangMasuk;
    private javax.swing.JTextField txtUangTransaksiBarangMasuk;
    // End of variables declaration//GEN-END:variables
}
