/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi;

import Controller.CPemesanan;
import Controller.CTableBarang;
import RTClass.Pemesanan;
import connection.DBConnect;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author rizky
 */
public class TransaksiPemesanan1 extends javax.swing.JFrame {
    DefaultTableModel model = new DefaultTableModel();
    DefaultTableModel model1 = new DefaultTableModel();
    CTableBarang controllerTable = new CTableBarang();
    CPemesanan controllerPemesanan = new CPemesanan();
    DBConnect connection = new DBConnect();
    Pemesanan psn = new Pemesanan();
    /**
     * Creates new form Pemesanan
     */
    
    public TransaksiPemesanan1(String nama, String posisi) {
        initComponents();
        
        lblnama.setText(nama);
        lbljabatan.setText(posisi);
        
        addColumn();
        addData();
        tblBarang.setModel(model);
        
        lebarKolom();
        tampilPelanggan();
        txtNamaPelanggan.setEnabled(false);
        txtJumlahBarang.setEnabled(false);
        txtJumlahKodi.setEnabled(false);
        txtTotal.setEnabled(false);
        lebarKolomKeranjang();
        
    }

    private void addData(){
        model.getDataVector().removeAllElements();

        model.fireTableDataChanged();
        
        model = controllerTable.addDataBarang(model);
    }
    
    private void addColumn(){
        model.addColumn("ID Barang");
        model.addColumn("Jenis Barang");
        model.addColumn("Deskripsi");
        model.addColumn("Bahan");
        model.addColumn("Ukuran");
        model.addColumn("Stok");
        model.addColumn("Harga Satuan");
        model.addColumn("Harga Kodian");
        model.addColumn("Harga Jual Satuan");
        model.addColumn("Harga Jual Kodian");
        model.addColumn("ID Pemasok");
    }
    
    public void clearPesanan(){
        cmbPelanggan.setSelectedIndex(0);
        txtNamaPelanggan.setText("");
        txtJumlahBarang.setText("");
        txtJumlahKodi.setText("");
        txtTotal.setText("");
    }
    
    public void lebarKolom(){ 
        TableColumn column;
        tblBarang.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tblBarang.getColumnModel().getColumn(0); 
        column.setPreferredWidth(100);
        column = tblBarang.getColumnModel().getColumn(1); 
        column.setPreferredWidth(100); 
        column = tblBarang.getColumnModel().getColumn(2); 
        column.setPreferredWidth(100); 
        column = tblBarang.getColumnModel().getColumn(3); 
        column.setPreferredWidth(50);
        column = tblBarang.getColumnModel().getColumn(4); 
        column.setPreferredWidth(50);
        column = tblBarang.getColumnModel().getColumn(5); 
        column.setPreferredWidth(50);
        column = tblBarang.getColumnModel().getColumn(6); 
        column.setPreferredWidth(150);
        column = tblBarang.getColumnModel().getColumn(7); 
        column.setPreferredWidth(150);
        column = tblBarang.getColumnModel().getColumn(8); 
        column.setPreferredWidth(150);
        column = tblBarang.getColumnModel().getColumn(9); 
        column.setPreferredWidth(150);
        column = tblBarang.getColumnModel().getColumn(10); 
        column.setPreferredWidth(100);
        
    }
    
    public void lebarKolomKeranjang(){ 
        TableColumn column;
        tblKeranjang.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tblKeranjang.getColumnModel().getColumn(0); 
        column.setPreferredWidth(100);
        column = tblKeranjang.getColumnModel().getColumn(1); 
        column.setPreferredWidth(150); 
        column = tblKeranjang.getColumnModel().getColumn(2); 
        column.setPreferredWidth(150); 
        column = tblKeranjang.getColumnModel().getColumn(3); 
        column.setPreferredWidth(150);
        column = tblKeranjang.getColumnModel().getColumn(4); 
        column.setPreferredWidth(100);
        column = tblKeranjang.getColumnModel().getColumn(5); 
        column.setPreferredWidth(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbPelanggan = new javax.swing.JComboBox<>();
        txtNamaPelanggan = new javax.swing.JTextField();
        pnlDataBarang = new javax.swing.JPanel();
        btnTambahKeranjang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKeranjang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        panelKiri = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnPemesanan = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnPengolahanData = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        user_navigation = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lbljabatan = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblnama = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtJumlahBarang = new javax.swing.JTextField();
        txtJumlahKodi = new javax.swing.JTextField();
        panelAtas = new javax.swing.JPanel();
        kananatas = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Nama Toko");

        jLabel3.setText("Nama Pelanggan");

        cmbPelanggan.setBackground(new java.awt.Color(149, 225, 225));
        cmbPelanggan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== Pilih Toko ==" }));
        cmbPelanggan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPelangganItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbPelanggan, 0, 253, Short.MAX_VALUE)
                    .addComponent(txtNamaPelanggan))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 109, -1, -1));

        pnlDataBarang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Barang", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        btnTambahKeranjang.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnTambahKeranjang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Keranjang.png"))); // NOI18N
        btnTambahKeranjang.setText("Tambah");
        btnTambahKeranjang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTambahKeranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahKeranjangActionPerformed(evt);
            }
        });

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBarang);

        javax.swing.GroupLayout pnlDataBarangLayout = new javax.swing.GroupLayout(pnlDataBarang);
        pnlDataBarang.setLayout(pnlDataBarangLayout);
        pnlDataBarangLayout.setHorizontalGroup(
            pnlDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataBarangLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTambahKeranjang)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlDataBarangLayout.setVerticalGroup(
            pnlDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTambahKeranjang)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlDataBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 262, -1, 570));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Keranjang"));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Barang", "Nama Barang", "Harga Jual Satuan", "Harga Jual Kodian", "Jumlah Barang", "Jumlah Kodi"
            }
        ));
        tblKeranjang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblKeranjangKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblKeranjang);
        if (tblKeranjang.getColumnModel().getColumnCount() > 0) {
            tblKeranjang.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblKeranjang.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblKeranjang.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblKeranjang.getColumnModel().getColumn(3).setPreferredWidth(200);
            tblKeranjang.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblKeranjang.getColumnModel().getColumn(5).setPreferredWidth(100);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(945, 109, -1, -1));

        jLabel1.setText("Rp. ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 570, -1, 30));

        txtTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTotalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtTotalMouseEntered(evt);
            }
        });
        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotalKeyReleased(evt);
            }
        });
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1316, 573, 160, -1));

        panelKiri.setBackground(new java.awt.Color(0, 102, 102));
        panelKiri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelKiriMouseClicked(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Supplier.png"))); // NOI18N
        jButton1.setText("Pemasokkan");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btnPemesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Pemesanan.png"))); // NOI18N
        btnPemesanan.setText("Pemesanan");
        btnPemesanan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPemesanan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemesananActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Pengiriman.png"))); // NOI18N
        jButton3.setText("Pengiriman");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btnPengolahanData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Kelola.png"))); // NOI18N
        btnPengolahanData.setText("Kelola Data");
        btnPengolahanData.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPengolahanData.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPengolahanData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengolahanDataActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Pembayaran.png"))); // NOI18N
        jButton5.setText("Pembayaran");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnKeluar.setText("KELUAR");

        user_navigation.setBackground(new java.awt.Color(0, 204, 204));
        user_navigation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        user_navigation.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/userTawal.png"))); // NOI18N

        lbljabatan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbljabatan.setForeground(new java.awt.Color(255, 255, 255));
        lbljabatan.setText("Posisi");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("______________");

        lblnama.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblnama.setForeground(new java.awt.Color(255, 255, 255));
        lblnama.setText("Nama");

        javax.swing.GroupLayout user_navigationLayout = new javax.swing.GroupLayout(user_navigation);
        user_navigation.setLayout(user_navigationLayout);
        user_navigationLayout.setHorizontalGroup(
            user_navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, user_navigationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(user_navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblnama, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbljabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        user_navigationLayout.setVerticalGroup(
            user_navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(user_navigationLayout.createSequentialGroup()
                .addGroup(user_navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(user_navigationLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblnama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(user_navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(user_navigationLayout.createSequentialGroup()
                                .addComponent(lbljabatan)
                                .addGap(12, 12, 12))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(user_navigationLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelKiriLayout = new javax.swing.GroupLayout(panelKiri);
        panelKiri.setLayout(panelKiriLayout);
        panelKiriLayout.setHorizontalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPengolahanData)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user_navigation, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelKiriLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnPemesanan, btnPengolahanData, jButton1, jButton3, jButton5});

        panelKiriLayout.setVerticalGroup(
            panelKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKiriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(user_navigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPemesanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPengolahanData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(btnKeluar)
                .addContainerGap())
        );

        panelKiriLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnPemesanan, btnPengolahanData, jButton1, jButton3, jButton5});

        getContentPane().add(panelKiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 760));

        btnSimpan.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Simpan Pesanan.png"))); // NOI18N
        btnSimpan.setText("Simpan Pesanan");
        btnSimpan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSimpan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1226, 629, 250, 55));

        jLabel6.setText("Total Jumlah Barang");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1091, 487, -1, -1));

        jLabel7.setText("Total Jumlah Kodi");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1091, 532, -1, -1));

        txtJumlahBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtJumlahBarangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtJumlahBarangMouseEntered(evt);
            }
        });
        txtJumlahBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJumlahBarangKeyReleased(evt);
            }
        });
        getContentPane().add(txtJumlahBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1285, 487, 191, -1));

        txtJumlahKodi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtJumlahKodiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtJumlahKodiMouseEntered(evt);
            }
        });
        getContentPane().add(txtJumlahKodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1285, 529, 191, -1));

        panelAtas.setBackground(new java.awt.Color(0, 204, 204));

        kananatas.setText("Batas kanan atas");

        jLabel8.setFont(new java.awt.Font("Lucida Handwriting", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("RTCollection");

        javax.swing.GroupLayout panelAtasLayout = new javax.swing.GroupLayout(panelAtas);
        panelAtas.setLayout(panelAtasLayout);
        panelAtasLayout.setHorizontalGroup(
            panelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtasLayout.createSequentialGroup()
                .addContainerGap(736, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(407, 407, 407)
                .addComponent(kananatas)
                .addGap(18, 18, 18))
        );
        panelAtasLayout.setVerticalGroup(
            panelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kananatas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtasLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        getContentPane().add(panelAtas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setText("Total Harga");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1091, 576, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahKeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahKeranjangActionPerformed
        // TODO add your handling code here:
        TableModel model1 = tblBarang.getModel();
        int indexs[] = tblBarang.getSelectedRows();
        
        Object[] row = new Object[4];
        DefaultTableModel model2 = (DefaultTableModel) tblKeranjang.getModel();
        
        for (int i = 0; i < indexs.length; i++){
            row[0] = model1.getValueAt(indexs[i], 0);
            row[1] = model1.getValueAt(indexs[i], 2);
            row[2] = model1.getValueAt(indexs[i], 8);
            row[3] = model1.getValueAt(indexs[i], 9);
            
            model2.addRow(row);
        }
    }//GEN-LAST:event_btnTambahKeranjangActionPerformed

    private void txtTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTotalMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTotalMouseClicked

    private void txtTotalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTotalMouseEntered
        // TODO add your handling code here:
        double temp1,temp2,temp3, total = 0.0;
        
        int i = tblKeranjang.getSelectedRow();
        if(i == -1){
            return;
        }
        int j = tblKeranjang.getModel().getRowCount();
        
        for (int k = 0; k < j; k++){
            temp1 = (Double.parseDouble((String) tblKeranjang.getValueAt(k, 3)));
            temp2 = (Double.parseDouble((String) tblKeranjang.getValueAt(k, 5)));
            temp3 = temp1 * temp2;
            total = total + temp3;
        }
        txtTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_txtTotalMouseEntered

    private void txtTotalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyReleased
        // TODO add your handling code here:
     
    }//GEN-LAST:event_txtTotalKeyReleased

    private void tblKeranjangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblKeranjangKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblKeranjangKeyReleased

    private void btnPengolahanDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengolahanDataActionPerformed
        // TODO add your handling code here:
//        if(!olah){
//            panelPengolahanData.setVisible(true);
//            panelDashboard.setVisible(false);
//            olah = true;
//        }else{
//            olah = false;
//            panelPengolahanData.setVisible(false);
//            panelDashboard.setVisible(true);
//        }
    }//GEN-LAST:event_btnPengolahanDataActionPerformed
    
    
    private void tampilPelanggan()
    {
         try{
           connection.stat = connection.conn.createStatement();
           String sql = "SELECT pgn_nama_toko,pgn_id FROM Pelanggan";
           connection.result = connection.stat.executeQuery(sql);
           
           while(connection.result.next()){
               cmbPelanggan.addItem(connection.result.getString("pgn_nama_toko"));
           }
           connection.stat.close();
           connection.result.close();
        }
        catch(SQLException ex)
        {
            System.out.println("Terjadi error saat load data pelanggan " + ex);
        }
    }
    
    private void panelKiriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelKiriMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, this.getSize().toString());
    }//GEN-LAST:event_panelKiriMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        int stock, stock2 = 0;
        SimpleDateFormat formatDate = new SimpleDateFormat("yyyyMMdd");
        String IdPelanggan = (String) cmbPelanggan.getSelectedItem();
        String namaKry = lblnama.getText();
        
        if (cmbPelanggan.getSelectedItem().equals("== Pilih Pelanggan ==") || txtTotal.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Data tidak boleh kosong!");
        }
        else{
        
            try{
                connection.stat = connection.conn.createStatement();
                String sql = "SELECT pgn_id,pgn_nama_toko FROM Pelanggan WHERE pgn_nama_toko = '" + cmbPelanggan.getSelectedItem() + "'";
                connection.result = connection.stat.executeQuery(sql);

                while (connection.result.next()){
                    IdPelanggan = connection.result.getString("pgn_id");
                }

                connection.stat = connection.conn.createStatement();
                String sql1 = "SELECT kry_id,kry_nama FROM Karyawan WHERE kry_nama = '" + lblnama.getText()+ "'";
                connection.result = connection.stat.executeQuery(sql1);

                while (connection.result.next()){
                    namaKry = connection.result.getString("kry_id");
                }


                    psn.setPmsn_id(formatDate.format(new Date()) +"-"+ controllerPemesanan.getLastID());
                    psn.setPgn_id(Integer.parseInt(IdPelanggan));
                    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");  
                    Date date = new Date();  
                    psn.setPmsn_tgl_transaksi(date);
                    psn.setPmsn_jumlah_barang(Integer.parseInt(txtJumlahBarang.getText()));
                    psn.setPmsn_jumlah_kodi(Integer.parseInt(txtJumlahKodi.getText()));
                    psn.setPmsn_total_uang(Double.parseDouble(txtTotal.getText()));
                    psn.setPmsn_Status("Disiapkan");
                    psn.setKry_id(namaKry);
                    controllerPemesanan.simpanPemesanan(psn);


                    for (int k = 0; k < tblKeranjang.getRowCount(); k++){
                        psn.setPmsn_id(psn.getPmsn_id());
                        psn.setb_id(Integer.parseInt( tblKeranjang.getValueAt(k, 0).toString()));
                        psn.setDetailJumlahBarang(Integer.parseInt( tblKeranjang.getValueAt(k, 4).toString()));
                        psn.setDetailJumlahKodi(Integer.parseInt( tblKeranjang.getValueAt(k, 5).toString()));
                        psn.setDetailHarga((Double.parseDouble(tblKeranjang.getValueAt(k, 3).toString())) * (Double.parseDouble(tblKeranjang.getValueAt(k, 5).toString())));

                        controllerPemesanan.simpanDetailPemesanan(psn);

                    }

                    JOptionPane.showMessageDialog(this, "Berhasil menambahkan pesanan..");
                    clearPesanan();
          
            }
            catch (SQLException ex){
                System.out.println("Terjadi error saat insert " + ex);
            } 
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void cmbPelangganItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPelangganItemStateChanged
        // TODO add your handling code here:
        try{
            DBConnect c = new DBConnect();
            c.stat = c.conn.createStatement();
            String sql = "SELECT * FROM Pelanggan";
            c.result = c.stat.executeQuery(sql);
            
            while (c.result.next()) {
                if(c.result.getString("pgn_nama_toko").equals(cmbPelanggan.getSelectedItem().toString())){
                    txtNamaPelanggan.setText(c.result.getString("pgn_nama"));
                }
            }
            c.stat.close();
            c.result.close();
            
        } catch (SQLException ex){
            System.out.println("Terjadi error"+ex);
        }
    }//GEN-LAST:event_cmbPelangganItemStateChanged

    
    private void txtJumlahBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJumlahBarangMouseClicked
        // TODO add your handling code here:
//        getSumJumlahBarang();
    }//GEN-LAST:event_txtJumlahBarangMouseClicked
    
    public void getSumJumlahBarang()
    {
        int sum = 0;
        for(int i = 0; i < tblKeranjang.getRowCount(); i++)
        {
            sum = sum + Integer.parseInt(tblKeranjang.getValueAt(i, 4).toString());
        }
        
        txtJumlahBarang.setText(Integer.toString(sum));
    }
    
    public void getSumJumlahKodi()
    {
        int sum = 0;
        for(int i = 0; i < tblKeranjang.getRowCount(); i++)
        {
            sum = sum + Integer.parseInt(tblKeranjang.getValueAt(i, 5).toString());
        }
        
        txtJumlahKodi.setText(Integer.toString(sum));
    }
    
    
    private void txtJumlahBarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJumlahBarangMouseEntered
        // TODO add your handling code here:
        getSumJumlahBarang();
    }//GEN-LAST:event_txtJumlahBarangMouseEntered

    private void txtJumlahBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahBarangKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahBarangKeyReleased

    private void txtJumlahKodiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJumlahKodiMouseEntered
        // TODO add your handling code here:
        getSumJumlahKodi();
    }//GEN-LAST:event_txtJumlahKodiMouseEntered

    private void txtJumlahKodiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJumlahKodiMouseClicked
        // TODO add your handling code here:
//        getSumJumlahKodi();
    }//GEN-LAST:event_txtJumlahKodiMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private boolean olah = false;
    private boolean pesanan = false;
    
    private void btnPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemesananActionPerformed
        // TODO add your handling code here:
        
        if(!pesanan){
            TransaksiPemesanan1 pesan = new TransaksiPemesanan1(lblnama.getText(), lbljabatan.getText());
            pesan.show();
            this.hide();
            pesanan = true;
        }else{
            pesanan = false;
            TransaksiPemesanan1 pesan = new TransaksiPemesanan1(lblnama.getText(), lbljabatan.getText());
            pesan.hide();
            this.show();
        }
    }//GEN-LAST:event_btnPemesananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiPemesanan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiPemesanan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiPemesanan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiPemesanan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiPemesanan1("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnPemesanan;
    private javax.swing.JButton btnPengolahanData;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambahKeranjang;
    private javax.swing.JComboBox<String> cmbPelanggan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel kananatas;
    private javax.swing.JLabel lbljabatan;
    private javax.swing.JLabel lblnama;
    private javax.swing.JPanel panelAtas;
    private javax.swing.JPanel panelKiri;
    private javax.swing.JPanel pnlDataBarang;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTable tblKeranjang;
    private javax.swing.JTextField txtJumlahBarang;
    private javax.swing.JTextField txtJumlahKodi;
    private javax.swing.JTextField txtNamaPelanggan;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JPanel user_navigation;
    // End of variables declaration//GEN-END:variables
}
