/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi;

import Controller.CPemasokkan;
import Controller.CPembayaran;
import Controller.CSupplier;
import Controller.CTable;
import RTClass.Pemasok;
import RTClass.Pembayaran;
import connection.DBConnect;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rizky
 */
public class TransaksiPembayaranPemasok extends javax.swing.JFrame {

    /**
     * Creates new form TransaksiPembayaranPemasok
     */
    //==========================DEKLARASI VARIABLE PEMBAYARAN PEMASOK =====================================
    public String kry_id = "";
    Pemasok pemasokPembayaranPemasok = new Pemasok();
    CSupplier ControllerPemasokPembayaranPemasok = new CSupplier();
    CTable ControllerTablePembayaranPemasok = new CTable();
    private DefaultTableModel modelPemasokPembayaranPemasok = new DefaultTableModel();
    CPembayaran ControllerPembayaranPembayaranPemasok = new CPembayaran();
    CPemasokkan ControllerPemasokkan = new CPemasokkan();
    
    DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
    DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
    
    private void addColumnPembayaranPemasok() {
        modelPemasokPembayaranPemasok.addColumn("No");
        modelPemasokPembayaranPemasok.addColumn("Nama");
        modelPemasokPembayaranPemasok.addColumn("Alamat");
        modelPemasokPembayaranPemasok.addColumn("No HP");
        modelPemasokPembayaranPemasok.addColumn("Transaksi");
        modelPemasokPembayaranPemasok.addColumn("Pembayaran");
        modelPemasokPembayaranPemasok.addColumn("Hutang");
    }
    
    private void addComboBoxPembayaranPemasok(){
        try {
            DBConnect connection = new DBConnect();
            connection.stat = connection.conn.createStatement();
            String query = "select * from Pemasok";
            connection.result = connection.stat.executeQuery(query);
            
            while (connection.result.next()) {
                
                cmbPemasokPembayaranPemasok.addItem(connection.result.getString("pms_nama"));
            }
            connection.stat.close();
            connection.result.close();
        } catch (Exception e) {
            System.out.println("Gagal111 addDataPemasok!\n" + e.toString());
        }
    }
    private void addDataPemasok(){
        
        modelPemasokPembayaranPemasok.getDataVector().removeAllElements();

        modelPemasokPembayaranPemasok.fireTableDataChanged();
        ControllerTablePembayaranPemasok.addDataPemasok(modelPemasokPembayaranPemasok,(String) cmbPemasokPembayaranPemasok.getSelectedItem());
    }
    private void ClearPembayaranPemasok() {

        txtNamaPemasokPembayaranPemasok.setText("-");
        txtJumlahTransaksiPemasokPembayaranPemasok.setText("0");
        txtHutangPemasokPembayaranPemasok.setText(kursIndonesia.format(0));

        txtSisaHutangPembayaranPemasok.setText(kursIndonesia.format(0));
        txtBayarPembayaranPemasok.setText(kursIndonesia.format(0));
        txtKembalianPembayaranPemasok.setText(kursIndonesia.format(0));

    }
    public TransaksiPembayaranPemasok() {
        initComponents();
        
        //==========================DEKLARASI VARIABLE PEMBAYARAN PEMASOK =====================================
        addColumnPembayaranPemasok();
        addComboBoxPembayaranPemasok();
        tablePemasokPembayaranPemasok.setModel(modelPemasokPembayaranPemasok);
        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(formatRp);
    }
    
    
    
    
    
    private void addData() {
        modelPemasokPembayaranPemasok.getDataVector().removeAllElements();

        modelPemasokPembayaranPemasok.fireTableDataChanged();

        modelPemasokPembayaranPemasok = ControllerTablePembayaranPemasok.addDataPemasok(modelPemasokPembayaranPemasok);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPembayaranPemasok = new javax.swing.JPanel();
        panelDaftarBarangMasuk = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePemasokPembayaranPemasok = new javax.swing.JTable();
        cmbPemasokPembayaranPemasok = new javax.swing.JComboBox<>();
        panelDeskripsiBarangMasuk = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNamaPemasokPembayaranPemasok = new javax.swing.JTextField();
        txtJumlahTransaksiPemasokPembayaranPemasok = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHutangPemasokPembayaranPemasok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBayarPembayaranPemasok = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSisaHutangPembayaranPemasok = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lblKeteranganPembayaranPembayaranPemasok = new javax.swing.JLabel();
        btnBatalPembayaranPemasok = new javax.swing.JButton();
        btnBayarPembayaranPemasok = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtKembalianPembayaranPemasok = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPembayaranPemasok.setMinimumSize(new java.awt.Dimension(1100, 652));
        panelPembayaranPemasok.setPreferredSize(new java.awt.Dimension(1100, 652));
        panelPembayaranPemasok.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDaftarBarangMasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("DAFTAR PEMASOK");

        tablePemasokPembayaranPemasok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePemasokPembayaranPemasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePemasokPembayaranPemasokMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePemasokPembayaranPemasok);

        cmbPemasokPembayaranPemasok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Pemasok -" }));
        cmbPemasokPembayaranPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPemasokPembayaranPemasokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDaftarBarangMasukLayout = new javax.swing.GroupLayout(panelDaftarBarangMasuk);
        panelDaftarBarangMasuk.setLayout(panelDaftarBarangMasukLayout);
        panelDaftarBarangMasukLayout.setHorizontalGroup(
            panelDaftarBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarBarangMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDaftarBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
                    .addGroup(panelDaftarBarangMasukLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbPemasokPembayaranPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelDaftarBarangMasukLayout.setVerticalGroup(
            panelDaftarBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarBarangMasukLayout.createSequentialGroup()
                .addGroup(panelDaftarBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPemasokPembayaranPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelPembayaranPemasok.add(panelDaftarBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1100, 400));

        panelDeskripsiBarangMasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDeskripsiBarangMasuk.setPreferredSize(new java.awt.Dimension(1100, 185));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("DESKRIPSI TRANSAKSI PEMBAYARAN PEMASOKKAN");

        jLabel2.setText("Nama");

        txtNamaPemasokPembayaranPemasok.setText("-");

        txtJumlahTransaksiPemasokPembayaranPemasok.setText("-");

        jLabel3.setText("Jumlah transaksi");

        jLabel5.setText("Hutang");

        txtHutangPemasokPembayaranPemasok.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHutangPemasokPembayaranPemasok.setText("Rp. 0,00");

        jLabel6.setText("Kembali ");

        txtBayarPembayaranPemasok.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBayarPembayaranPemasok.setText("0");
        txtBayarPembayaranPemasok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBayarPembayaranPemasokKeyReleased(evt);
            }
        });

        jLabel9.setText("Rp");

        jLabel10.setText("Sisa hutang pada pemasok");

        txtSisaHutangPembayaranPemasok.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSisaHutangPembayaranPemasok.setText("Rp. 0,00");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("KETERANGAN PEMBAYARAN");

        lblKeteranganPembayaranPembayaranPemasok.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblKeteranganPembayaranPembayaranPemasok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeteranganPembayaranPembayaranPemasok.setText("[Keterangan]");
        lblKeteranganPembayaranPembayaranPemasok.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnBatalPembayaranPemasok.setText("Batal");
        btnBatalPembayaranPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalPembayaranPemasokActionPerformed(evt);
            }
        });

        btnBayarPembayaranPemasok.setText("Bayar");
        btnBayarPembayaranPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarPembayaranPemasokActionPerformed(evt);
            }
        });

        jLabel11.setText("Banyak uang dibayar");

        txtKembalianPembayaranPemasok.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtKembalianPembayaranPemasok.setText("0");
        txtKembalianPembayaranPemasok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKembalianPembayaranPemasokKeyReleased(evt);
            }
        });

        jLabel13.setText("Rp");

        javax.swing.GroupLayout panelDeskripsiBarangMasukLayout = new javax.swing.GroupLayout(panelDeskripsiBarangMasuk);
        panelDeskripsiBarangMasuk.setLayout(panelDeskripsiBarangMasukLayout);
        panelDeskripsiBarangMasukLayout.setHorizontalGroup(
            panelDeskripsiBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeskripsiBarangMasukLayout.createSequentialGroup()
                .addGroup(panelDeskripsiBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDeskripsiBarangMasukLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelDeskripsiBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelDeskripsiBarangMasukLayout.createSequentialGroup()
                                .addGroup(panelDeskripsiBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDeskripsiBarangMasukLayout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNamaPemasokPembayaranPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelDeskripsiBarangMasukLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtJumlahTransaksiPemasokPembayaranPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelDeskripsiBarangMasukLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtHutangPemasokPembayaranPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(7, 7, 7)))
                        .addGap(23, 23, 23)
                        .addGroup(panelDeskripsiBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addGroup(panelDeskripsiBarangMasukLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(15, 15, 15)
                                .addComponent(txtBayarPembayaranPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(txtSisaHutangPembayaranPemasok)))
                    .addGroup(panelDeskripsiBarangMasukLayout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(jLabel9)
                        .addGap(15, 15, 15)
                        .addComponent(txtKembalianPembayaranPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panelDeskripsiBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDeskripsiBarangMasukLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(panelDeskripsiBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDeskripsiBarangMasukLayout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jLabel12))
                            .addComponent(lblKeteranganPembayaranPembayaranPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDeskripsiBarangMasukLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDeskripsiBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBayarPembayaranPemasok, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                            .addComponent(btnBatalPembayaranPemasok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        panelDeskripsiBarangMasukLayout.setVerticalGroup(
            panelDeskripsiBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeskripsiBarangMasukLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelDeskripsiBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDeskripsiBarangMasukLayout.createSequentialGroup()
                        .addGroup(panelDeskripsiBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDeskripsiBarangMasukLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(panelDeskripsiBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNamaPemasokPembayaranPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(panelDeskripsiBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(panelDeskripsiBarangMasukLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(txtJumlahTransaksiPemasokPembayaranPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(16, 16, 16)
                                .addGroup(panelDeskripsiBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtHutangPemasokPembayaranPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelDeskripsiBarangMasukLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel11)
                                .addGap(14, 14, 14)
                                .addGroup(panelDeskripsiBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(txtBayarPembayaranPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addComponent(jLabel10)
                                .addGap(14, 14, 14)
                                .addComponent(txtSisaHutangPembayaranPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6)))
                        .addGap(4, 4, 4)
                        .addGroup(panelDeskripsiBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtKembalianPembayaranPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDeskripsiBarangMasukLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12)
                        .addGap(3, 3, 3)
                        .addComponent(lblKeteranganPembayaranPembayaranPemasok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBayarPembayaranPemasok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatalPembayaranPemasok)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelPembayaranPemasok.add(panelDeskripsiBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 1100, 210));

        getContentPane().add(panelPembayaranPemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablePemasokPembayaranPemasokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePemasokPembayaranPemasokMouseClicked
        // TODO add your handling code here:
        ClearPembayaranPemasok();
        pemasokPembayaranPemasok = ControllerTablePembayaranPemasok.getSelectedRowPemasok(tablePemasokPembayaranPemasok);
        txtNamaPemasokPembayaranPemasok.setText(pemasokPembayaranPemasok.getPms_nama());
        txtJumlahTransaksiPemasokPembayaranPemasok.setText(Integer.toString(pemasokPembayaranPemasok.getPms_jumlah_transaksi()));
        txtHutangPemasokPembayaranPemasok.setText(kursIndonesia.format(pemasokPembayaranPemasok.getPms_total_hutang()));
        int status = pemasokPembayaranPemasok.getPms_uang_transaksi();
        
        if ( pemasokPembayaranPemasok.getPms_total_hutang() == 0){
            lblKeteranganPembayaranPembayaranPemasok.setText("LUNAS");
            if (lblKeteranganPembayaranPembayaranPemasok.getText().equals("LUNAS"))
            {
                btnBayarPembayaranPemasok.setEnabled(false);
            }
        }
        else{
            lblKeteranganPembayaranPembayaranPemasok.setText("BELUM LUNAS");
        }

    }//GEN-LAST:event_tablePemasokPembayaranPemasokMouseClicked

    private void txtBayarPembayaranPemasokKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBayarPembayaranPemasokKeyReleased
        // TODO add your handling code here:
        
        if (txtBayarPembayaranPemasok.getText().equals("")) {
            txtSisaHutangPembayaranPemasok.setText(txtHutangPemasokPembayaranPemasok.getText());
            return;
        }

        try {
           
            txtSisaHutangPembayaranPemasok.setText(kursIndonesia.format(((long) kursIndonesia.parse(txtHutangPemasokPembayaranPemasok.getText())) - Long.parseLong(txtBayarPembayaranPemasok.getText())));
            txtKembalianPembayaranPemasok.setText(kursIndonesia.format((Long.parseLong(txtBayarPembayaranPemasok.getText())) - (long) kursIndonesia.parse(txtHutangPemasokPembayaranPemasok.getText())));
            
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_txtBayarPembayaranPemasokKeyReleased

    private void btnBatalPembayaranPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalPembayaranPemasokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalPembayaranPemasokActionPerformed

    private void btnBayarPembayaranPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarPembayaranPemasokActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat date = new SimpleDateFormat("ddMMyyyy");
        
        Pembayaran pembayaran = new Pembayaran();
        pembayaran.setBpmsk_id(ControllerPembayaranPembayaranPemasok.getLastID());
        pembayaran.setPms_id(ControllerTablePembayaranPemasok.getPemasokId((String)cmbPemasokPembayaranPemasok.getSelectedItem()));
        pembayaran.setKry_id("202006290001");
        pembayaran.setBpmsk_tgl_transaksi(new Date());
        pembayaran.setBpmsk_uang_dibayar(Integer.valueOf(txtBayarPembayaranPemasok.getText()));
        
        ControllerPembayaranPembayaranPemasok.simpanPembayaranPemasok(pembayaran);
        try {
            ControllerPemasokPembayaranPemasok.updateTransaksiPembayaran(Long.parseLong(txtBayarPembayaranPemasok.getText()), Long.parseLong((kursIndonesia.parse(txtSisaHutangPembayaranPemasok.getText())).toString()), pemasokPembayaranPemasok.getPms_id().toString());
            
            ControllerTablePembayaranPemasok.addDataPemasok(modelPemasokPembayaranPemasok,(String) cmbPemasokPembayaranPemasok.getSelectedItem());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Tidak dapat menyimpan ke pemasok!");
        }
        
        JOptionPane.showMessageDialog(this, "Pembayaran berhasil....");
        addDataPemasok();
        ClearPembayaranPemasok();
        cmbPemasokPembayaranPemasok.setSelectedIndex(0);
        lblKeteranganPembayaranPembayaranPemasok.setText("[Keterangan]");
    }//GEN-LAST:event_btnBayarPembayaranPemasokActionPerformed

    
    
    private void cmbPemasokPembayaranPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPemasokPembayaranPemasokActionPerformed
        // TODO add your handling code here:
        modelPemasokPembayaranPemasok.getDataVector().removeAllElements();

        modelPemasokPembayaranPemasok.fireTableDataChanged();
        ClearPembayaranPemasok();
        ControllerTablePembayaranPemasok.addDataPemasok(modelPemasokPembayaranPemasok,(String) cmbPemasokPembayaranPemasok.getSelectedItem());
    }//GEN-LAST:event_cmbPemasokPembayaranPemasokActionPerformed

    private void txtKembalianPembayaranPemasokKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKembalianPembayaranPemasokKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKembalianPembayaranPemasokKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiPembayaranPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiPembayaranPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiPembayaranPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiPembayaranPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiPembayaranPemasok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalPembayaranPemasok;
    private javax.swing.JButton btnBayarPembayaranPemasok;
    private javax.swing.JComboBox<String> cmbPemasokPembayaranPemasok;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKeteranganPembayaranPembayaranPemasok;
    private javax.swing.JPanel panelDaftarBarangMasuk;
    private javax.swing.JPanel panelDeskripsiBarangMasuk;
    private javax.swing.JPanel panelPembayaranPemasok;
    private javax.swing.JTable tablePemasokPembayaranPemasok;
    private javax.swing.JTextField txtBayarPembayaranPemasok;
    private javax.swing.JTextField txtHutangPemasokPembayaranPemasok;
    private javax.swing.JTextField txtJumlahTransaksiPemasokPembayaranPemasok;
    private javax.swing.JTextField txtKembalianPembayaranPemasok;
    private javax.swing.JTextField txtNamaPemasokPembayaranPemasok;
    private javax.swing.JTextField txtSisaHutangPembayaranPemasok;
    // End of variables declaration//GEN-END:variables
}
