/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi;

import Controller.CBarang;
import Controller.CPemasokkan;
import Controller.CTable;
import Controller.CTableBarang;
import RTClass.Barang;
import RTClass.DetailPemasokkan;
import RTClass.Pemasok;
import RTClass.Pemasokkan;
import connection.DBConnect;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Polman
 */
public class TransaksiPemasokkan extends javax.swing.JFrame {

    /**
     * Creates new form Pemasokkan
     */
    
    
    
    //Variable Pemasokkan
    int TotalHarga = 0;
    int Harga = 0;
    int TotalBiaya = 0;
    public String kry_id = "";
    private DefaultTableModel modelBarang = new DefaultTableModel();
    private DefaultTableModel modelKeranjang = new DefaultTableModel();    
    CTableBarang ControllerBarang = new CTableBarang();
    CTable ControllerPemasok = new CTable();
    CPemasokkan ControllerPemasokkan = new CPemasokkan();
    Barang barang = new Barang();
    SimpleDateFormat formatTanggal = new SimpleDateFormat("dd-MM-yyyy");
    DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
    DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
    
    public TransaksiPemasokkan() {
        initComponents();
        
        tableBarang.setModel(modelBarang);
        tableKeranjang.setModel(modelKeranjang);
        txtTanggal.setText(formatTanggal.format(new Date()));
        
        
        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(formatRp);
        
        addColumn();
        addComboBox();
    }
    private void addComboBox(){
        try {
            DBConnect connection = new DBConnect();
            connection.stat = connection.conn.createStatement();
            String query = "select * from Pemasok";
            connection.result = connection.stat.executeQuery(query);
            
            while (connection.result.next()) {
                
                cmbPemasok.addItem(connection.result.getString("pms_nama"));
            }
            connection.stat.close();
            connection.result.close();
        } catch (Exception e) {
            System.out.println("Gagal111 addDataPemasok!\n" + e.toString());
        }
    }
    private void addDataBarang(String pemasok){
        
        modelBarang.getDataVector().removeAllElements();

        modelBarang.fireTableDataChanged();
        ControllerBarang.addDataBarangRestock(modelBarang,pemasok);
    }
    
    private void addColumn() {
        modelBarang.addColumn("No");
        modelBarang.addColumn("Barang");
        modelBarang.addColumn("Jenis");
        modelBarang.addColumn("Ukuran");
        modelBarang.addColumn("Stock");
        modelBarang.addColumn("Pemasok");
        
        modelKeranjang.addColumn("No");
        modelKeranjang.addColumn("Barang");
        modelKeranjang.addColumn("Ukuran");
        modelKeranjang.addColumn("Pemasok");
        modelKeranjang.addColumn("Jumlah");
        modelKeranjang.addColumn("Harga");
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBarang = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBarang = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        cmbPemasok = new javax.swing.JComboBox<>();
        panelDeskripsi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        panelDetailBeli = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBarang = new javax.swing.JTextField();
        txtPemasok = new javax.swing.JTextField();
        Ukuran = new javax.swing.JLabel();
        Ukuran1 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JSpinner();
        Ukuran2 = new javax.swing.JLabel();
        txtTotalHarga = new javax.swing.JTextField();
        btnKeranjang = new javax.swing.JButton();
        txtUkuran = new javax.swing.JTextField();
        panelKeranjang = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableKeranjang = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Ukuran3 = new javax.swing.JLabel();
        txtjumlah_kodi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTotalBiaya = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(null);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBarang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBarang);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("TABLE PEMASOK");

        cmbPemasok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Pemasok -" }));
        cmbPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPemasokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBarang.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 640));

        panelDeskripsi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("DESKRIPSI PEMASOKAN");

        jLabel2.setText("Tanggal Transaksi");

        javax.swing.GroupLayout panelDeskripsiLayout = new javax.swing.GroupLayout(panelDeskripsi);
        panelDeskripsi.setLayout(panelDeskripsiLayout);
        panelDeskripsiLayout.setHorizontalGroup(
            panelDeskripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeskripsiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDeskripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        panelDeskripsiLayout.setVerticalGroup(
            panelDeskripsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeskripsiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        panelBarang.add(panelDeskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 590, 100));

        panelDetailBeli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDetailBeli.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("DESKRIPSI DETAIL PEMASOKKAN");

        jLabel4.setText("Barang");

        txtBarang.setEnabled(false);

        txtPemasok.setEnabled(false);
        txtPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPemasokActionPerformed(evt);
            }
        });

        Ukuran.setText("Pemasok");

        Ukuran1.setText("Jumlah Kodi");

        txtJumlah.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        txtJumlah.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtJumlahStateChanged(evt);
            }
        });
        txtJumlah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtJumlahMouseClicked(evt);
            }
        });
        txtJumlah.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtJumlahPropertyChange(evt);
            }
        });

        Ukuran2.setText("Total Harga");

        txtTotalHarga.setEnabled(false);
        txtTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalHargaActionPerformed(evt);
            }
        });

        btnKeranjang.setText("Masukkan ke keranjang");
        btnKeranjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeranjangActionPerformed(evt);
            }
        });

        txtUkuran.setEnabled(false);

        javax.swing.GroupLayout panelDetailBeliLayout = new javax.swing.GroupLayout(panelDetailBeli);
        panelDetailBeli.setLayout(panelDetailBeliLayout);
        panelDetailBeliLayout.setHorizontalGroup(
            panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailBeliLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDetailBeliLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(panelDetailBeliLayout.createSequentialGroup()
                        .addGroup(panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPemasok)
                            .addGroup(panelDetailBeliLayout.createSequentialGroup()
                                .addComponent(Ukuran, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)))
                .addGroup(panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetailBeliLayout.createSequentialGroup()
                        .addGroup(panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ukuran1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ukuran2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetailBeliLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnKeranjang)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDetailBeliLayout.setVerticalGroup(
            panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailBeliLayout.createSequentialGroup()
                .addGroup(panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetailBeliLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKeranjang, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(Ukuran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDetailBeliLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDetailBeliLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ukuran1)
                            .addComponent(Ukuran2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDetailBeliLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel4)))
                .addGap(12, 12, Short.MAX_VALUE))
        );

        panelBarang.add(panelDetailBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 590, -1));

        panelKeranjang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableKeranjang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKeranjangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableKeranjang);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("DAFTAR PEMASOKKAN");

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Ukuran3.setText("Total Harga");

        txtjumlah_kodi.setText("jTextField1");

        jLabel6.setText("Jumlah Kodi Barang");

        txtTotalBiaya.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtTotalBiaya.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTotalBiaya.setText("jLabel7");

        javax.swing.GroupLayout panelKeranjangLayout = new javax.swing.GroupLayout(panelKeranjang);
        panelKeranjang.setLayout(panelKeranjangLayout);
        panelKeranjangLayout.setHorizontalGroup(
            panelKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKeranjangLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panelKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTotalBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(panelKeranjangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtjumlah_kodi))
                .addGap(190, 190, 190)
                .addComponent(Ukuran3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177))
        );
        panelKeranjangLayout.setVerticalGroup(
            panelKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKeranjangLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panelKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKeranjangLayout.createSequentialGroup()
                        .addGroup(panelKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Ukuran3))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKeranjangLayout.createSequentialGroup()
                        .addGroup(panelKeranjangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtjumlah_kodi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalBiaya))
                        .addContainerGap())))
        );

        panelBarang.add(panelKeranjang, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 590, 370));

        btnProses.setText("Proses Pemasokkan");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        panelBarang.add(btnProses, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 620, -1, -1));

        getContentPane().add(panelBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPemasokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPemasokActionPerformed

    private void txtTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalHargaActionPerformed

    private void tableBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBarangMouseClicked
        // TODO add your handling code here:
        barang = ControllerBarang.getSelectedRowBarangPemasokkan(tableBarang);
        
        txtBarang.setText(barang.getNama_Barang());
        txtUkuran.setText(barang.getUkuran_Barang());
        txtPemasok.setText(ControllerPemasok.getPemasokNama(String.valueOf(barang.getPmsk_Barang())));
        TotalHarga = (int) Math.round(barang.getHargaKodian_Barang());
        Harga = (int) Math.round(barang.getHargaKodian_Barang());
        txtTotalHarga.setText(kursIndonesia.format((int) Math.round(barang.getHargaKodian_Barang())));
    }//GEN-LAST:event_tableBarangMouseClicked

    private void txtJumlahPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtJumlahPropertyChange
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtJumlahPropertyChange

    private void txtJumlahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJumlahMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtJumlahMouseClicked

    private void txtJumlahStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtJumlahStateChanged
        // TODO add your handling code here:
        try{
            int jumlah = Integer.parseInt(txtJumlah.getValue().toString());
            TotalHarga = jumlah * Harga;
            txtTotalHarga.setText(kursIndonesia.format((TotalHarga)));
            
            //System.out.println(total);
        }catch(Exception ex){
            System.out.println("Error cuy txtJumlahPropertyChange "+ex);
        }
    }//GEN-LAST:event_txtJumlahStateChanged

    private void btnKeranjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeranjangActionPerformed
        // TODO add your handling code here:
        if(txtBarang.getText().equals("")){
            return;
        }
        for(int i = 0 ; i < modelKeranjang.getRowCount() ; i ++){
            if(modelKeranjang.getValueAt(i, 1).toString().equals(txtBarang.getText()) && modelKeranjang.getValueAt(i, 2).toString().equals(txtUkuran.getText())){
                modelKeranjang.removeRow(i);
            }
        }
        Object[] rowData = new Object[]{modelKeranjang.getRowCount()+1,txtBarang.getText(),txtUkuran.getText(),txtPemasok.getText(),txtJumlah.getValue(),TotalHarga};
        modelKeranjang.addRow(rowData);
        clear();
        hitungTotal();
        hitungKodi();
    }//GEN-LAST:event_btnKeranjangActionPerformed
    private void clear(){
        txtBarang.setText("");
        txtJumlah.setValue(1);
        txtPemasok.setText("");
        txtTotalHarga.setText("");
        txtUkuran.setText("");
        hitungKodi();
        hitungTotal();
    }
    private void hitungTotal(){
        int total = 0;
        for(int i = 0 ; i < modelKeranjang.getRowCount();i++){
            total = total +(int) modelKeranjang.getValueAt(i, 5);
        }
        txtTotalBiaya.setText(kursIndonesia.format(total));
        TotalBiaya = total;
    }
    private void hitungKodi(){
        int total = 0;
        for(int i = 0 ; i < modelKeranjang.getRowCount();i++){
            total = total +(int) modelKeranjang.getValueAt(i, 4);
        }
        txtjumlah_kodi.setText(Integer.toString(total));
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        modelKeranjang.getDataVector().removeAllElements();

        modelKeranjang.fireTableDataChanged();
        clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat date = new SimpleDateFormat("ddMMyyyy");
        
        Pemasokkan pemasokkan = new Pemasokkan();
        pemasokkan.setPmsk_id(ControllerPemasokkan.getLastID());
        pemasokkan.setPms_id(ControllerPemasok.getPemasokId((String)cmbPemasok.getSelectedItem()));
        pemasokkan.setPmsk_jumlah_barang(Integer.valueOf(txtjumlah_kodi.getText())*20);
        pemasokkan.setPmsk_jumlah_kodi(Integer.valueOf(txtjumlah_kodi.getText()));
        pemasokkan.setPmsk_tgl_transaksi(new Date());
        pemasokkan.setPmsk_uang_dibayar(0);
        pemasokkan.setPmsk_total_uang(TotalBiaya);
        //pemasokkan.setKry_id("202007010002");
        pemasokkan.setKry_id(kry_id);
        pemasokkan.setStatus("Proses");
        
        System.out.println(pemasokkan.getAllData());
        ControllerPemasokkan.simpanPemasokkan(pemasokkan);
        DetailPemasokkan detailPemasok = new DetailPemasokkan();
        detailPemasok.setPmsk_id(pemasokkan.getPmsk_id());
        for(int i = 0 ; i < tableKeranjang.getRowCount();i++){
            barang = ControllerBarang.getDatabyNamaUkuran(modelKeranjang.getValueAt(i, 1).toString(), modelKeranjang.getValueAt(i, 2).toString());
            detailPemasok.setB_id(Integer.toString(barang.getID_Barang()));
            detailPemasok.setDetail_jumlah_kodi((int)modelKeranjang.getValueAt(i, 4));
            detailPemasok.setDetail_jumlah_barang(((int)modelKeranjang.getValueAt(i, 4)) * 20);
            detailPemasok.setDetail_harga((int)modelKeranjang.getValueAt(i, 5));
            ControllerPemasokkan.simpanDetailPemasokkan(detailPemasok);
        }
        JOptionPane.showMessageDialog(this, "Berhasil memporses....");
    }//GEN-LAST:event_btnProsesActionPerformed

    private void cmbPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPemasokActionPerformed
        // TODO add your handling code here:
        modelKeranjang.getDataVector().removeAllElements();

        modelKeranjang.fireTableDataChanged();
        clear();
        addDataBarang((String) cmbPemasok.getSelectedItem());
    }//GEN-LAST:event_cmbPemasokActionPerformed

    private void tableKeranjangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKeranjangMouseClicked
        // TODO add your handling code here:
        barang = ControllerBarang.getSelectedRowBarangPemasokkan(tableBarang);
        
        txtBarang.setText((String) tableKeranjang.getValueAt(tableKeranjang.getSelectedRow(), 1));
        txtUkuran.setText((String) tableKeranjang.getValueAt(tableKeranjang.getSelectedRow(), 2));
        txtPemasok.setText((String) tableKeranjang.getValueAt(tableKeranjang.getSelectedRow(), 3));
        Harga = (int) Math.round(barang.getHargaKodian_Barang());
        txtTotalHarga.setText(kursIndonesia.format((int) Math.round(barang.getHargaKodian_Barang())));
    }//GEN-LAST:event_tableKeranjangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiPemasokkan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiPemasokkan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiPemasokkan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiPemasokkan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiPemasokkan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ukuran;
    private javax.swing.JLabel Ukuran1;
    private javax.swing.JLabel Ukuran2;
    private javax.swing.JLabel Ukuran3;
    private javax.swing.JButton btnKeranjang;
    private javax.swing.JButton btnProses;
    private javax.swing.JComboBox<String> cmbPemasok;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelBarang;
    private javax.swing.JPanel panelDeskripsi;
    private javax.swing.JPanel panelDetailBeli;
    private javax.swing.JPanel panelKeranjang;
    private javax.swing.JTable tableBarang;
    private javax.swing.JTable tableKeranjang;
    private javax.swing.JTextField txtBarang;
    private javax.swing.JSpinner txtJumlah;
    private javax.swing.JTextField txtPemasok;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JLabel txtTotalBiaya;
    private javax.swing.JTextField txtTotalHarga;
    private javax.swing.JTextField txtUkuran;
    private javax.swing.JTextField txtjumlah_kodi;
    // End of variables declaration//GEN-END:variables

    
}
