/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi;

import Controller.CPelanggan;
import Controller.CPemesanan;
import Controller.CPengiriman;
import Controller.CTableBarang;
import connection.DBConnect;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Polman
 */
public class TransaksiKonfirmasiBarangKeluar extends javax.swing.JFrame {

    /**
     * Creates new form TransaksiKonfirmasiBarangKeluar
     */
    public TransaksiKonfirmasiBarangKeluar() {

        initComponents();
        instantiateKonfirmasiKeluar();
    }
    //==========================DEKLARASI VARIABLE BARANG KELUAR =====================================
    private DefaultTableModel modelPengirimanKonfirmasiKeluar = new DefaultTableModel();
    private DefaultTableModel modelDetailKarungKonfirmasiKeluar = new DefaultTableModel();

    CTableBarang ControllerKonfirmasiKeluar = new CTableBarang();
    CPengiriman ControllerPengirimanKonfirmasiKeluar = new CPengiriman();
    CPemesanan ControllerPemesananKonfirmasiKeluar = new CPemesanan();
    CPelanggan ControllerPelangganKonfirmasiBarang = new CPelanggan();

    

    private void instantiateKonfirmasiKeluar() {
        addColumnKonfirmasiKeluar();
        tableKarungKonfirmasiKeluar.setModel(modelDetailKarungKonfirmasiKeluar);
        tablePengirimanKonfirmasiKeluar.setModel(modelPengirimanKonfirmasiKeluar);
        ButtonGroup a = new ButtonGroup();
        a.add(rbGagalKonfirmasiKeluar);
        a.add(rbDiterimaKonfirmasiKeluar);

        addDataKonfirmasiKeluar(0);
        addComboBoxKonfirmasiBarangKeluar();
    }

    private void addComboBoxKonfirmasiBarangKeluar() {
        try {
            DBConnect connection = new DBConnect();
            connection.stat = connection.conn.createStatement();
            String query = "select * from Pelanggan";
            connection.result = connection.stat.executeQuery(query);

            while (connection.result.next()) {

                cmbNamaPelangganKonfirmasiKeluar.addItem(connection.result.getString("pgn_nama"));
            }
            connection.stat.close();
            connection.result.close();
        } catch (Exception e) {
            System.out.println("Gagal111 addDataPemasok!\n" + e.toString());
        }
    }

    private void addDataKonfirmasiKeluar(int i) {
        modelPengirimanKonfirmasiKeluar.getDataVector().clear();
        modelDetailKarungKonfirmasiKeluar.getDataVector().clear();
        modelDetailKarungKonfirmasiKeluar.fireTableDataChanged();
        if (i == 0) {
            ControllerKonfirmasiKeluar.addkonfirmasiBarangKeluar(modelPengirimanKonfirmasiKeluar, "Semua");
        } else {
            ControllerKonfirmasiKeluar.addkonfirmasiBarangKeluar(modelPengirimanKonfirmasiKeluar, cmbNamaPelangganKonfirmasiKeluar.getSelectedItem().toString());
        }
        modelPengirimanKonfirmasiKeluar.fireTableDataChanged();
        txtNamaPelangganKonfirmasiKeluar.setText("-");
        txtKodeTransaksiKonfirmasiKeluar.setText("-");
    }

    private void addColumnKonfirmasiKeluar() {
        modelPengirimanKonfirmasiKeluar.addColumn("No");
        modelPengirimanKonfirmasiKeluar.addColumn("Kode");
        modelPengirimanKonfirmasiKeluar.addColumn("Pelanggan");
        modelPengirimanKonfirmasiKeluar.addColumn("Jumlah Barang");
        modelPengirimanKonfirmasiKeluar.addColumn("Jumlah Kodi");
        modelPengirimanKonfirmasiKeluar.addColumn("Jumlah Karung");
        modelPengirimanKonfirmasiKeluar.addColumn("Tanggal");
        modelPengirimanKonfirmasiKeluar.addColumn("Pengemudi");
        modelPengirimanKonfirmasiKeluar.addColumn("Status");

        modelDetailKarungKonfirmasiKeluar.addColumn("No");
        modelDetailKarungKonfirmasiKeluar.addColumn("Kode Karung");
        modelDetailKarungKonfirmasiKeluar.addColumn("Barang");
        modelDetailKarungKonfirmasiKeluar.addColumn("Ukuran");
        modelDetailKarungKonfirmasiKeluar.addColumn("Jumlah Barang");
        modelDetailKarungKonfirmasiKeluar.addColumn("Jumlah Kodi");
        modelDetailKarungKonfirmasiKeluar.addColumn("Keterangan");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePengirimanKonfirmasiKeluar = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableKarungKonfirmasiKeluar = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        rbDiterimaKonfirmasiKeluar = new javax.swing.JRadioButton();
        rbGagalKonfirmasiKeluar = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtNamaPelangganKonfirmasiKeluar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtKodeTransaksiKonfirmasiKeluar = new javax.swing.JTextField();
        btnKonfirmasiKonfirmasiKeluar = new javax.swing.JButton();
        txtStatusPengirimanKonfirmasiKeluar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cmbNamaPelangganKonfirmasiKeluar = new javax.swing.JComboBox<>();
        btnSemuaKonfirmasiKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("KONFIRMASI PENGIRIMAN BARANG");

        tablePengirimanKonfirmasiKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePengirimanKonfirmasiKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePengirimanKonfirmasiKeluarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePengirimanKonfirmasiKeluar);

        tableKarungKonfirmasiKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableKarungKonfirmasiKeluar.setEnabled(false);
        jScrollPane2.setViewportView(tableKarungKonfirmasiKeluar);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("DATA PENGIRIMAN");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("DATA DETAIL PENGIRIMAN");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("AKSI");

        rbDiterimaKonfirmasiKeluar.setSelected(true);
        rbDiterimaKonfirmasiKeluar.setText("Diterima");
        rbDiterimaKonfirmasiKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDiterimaKonfirmasiKeluarActionPerformed(evt);
            }
        });

        rbGagalKonfirmasiKeluar.setText("Gagal");
        rbGagalKonfirmasiKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGagalKonfirmasiKeluarActionPerformed(evt);
            }
        });

        jLabel5.setText("Nama Pelanggan");

        txtNamaPelangganKonfirmasiKeluar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNamaPelangganKonfirmasiKeluar.setText("-");
        txtNamaPelangganKonfirmasiKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaPelangganKonfirmasiKeluarActionPerformed(evt);
            }
        });
        txtNamaPelangganKonfirmasiKeluar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtNamaPelangganKonfirmasiKeluarPropertyChange(evt);
            }
        });

        jLabel6.setText("Kode Transaksi");

        txtKodeTransaksiKonfirmasiKeluar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtKodeTransaksiKonfirmasiKeluar.setText("-");
        txtKodeTransaksiKonfirmasiKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeTransaksiKonfirmasiKeluarActionPerformed(evt);
            }
        });
        txtKodeTransaksiKonfirmasiKeluar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtKodeTransaksiKonfirmasiKeluarPropertyChange(evt);
            }
        });

        btnKonfirmasiKonfirmasiKeluar.setText("KONFIRMASI");
        btnKonfirmasiKonfirmasiKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmasiKonfirmasiKeluarActionPerformed(evt);
            }
        });

        txtStatusPengirimanKonfirmasiKeluar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtStatusPengirimanKonfirmasiKeluar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStatusPengirimanKonfirmasiKeluar.setText("Diterima");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rbGagalKonfirmasiKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbDiterimaKonfirmasiKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKodeTransaksiKonfirmasiKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNamaPelangganKonfirmasiKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKonfirmasiKonfirmasiKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(txtStatusPengirimanKonfirmasiKeluar))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbDiterimaKonfirmasiKeluar)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbGagalKonfirmasiKeluar)
                            .addComponent(txtNamaPelangganKonfirmasiKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKodeTransaksiKonfirmasiKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtStatusPengirimanKonfirmasiKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKonfirmasiKonfirmasiKeluar)))
                .addContainerGap())
        );

        jLabel16.setText("Pelanggan");

        cmbNamaPelangganKonfirmasiKeluar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Pelanggan -" }));
        cmbNamaPelangganKonfirmasiKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNamaPelangganKonfirmasiKeluarActionPerformed(evt);
            }
        });

        btnSemuaKonfirmasiKeluar.setText("Semua");
        btnSemuaKonfirmasiKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSemuaKonfirmasiKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(216, 216, 216)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSemuaKonfirmasiKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbNamaPelangganKonfirmasiKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(458, 458, 458)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(cmbNamaPelangganKonfirmasiKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSemuaKonfirmasiKeluar))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbNamaPelangganKonfirmasiKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNamaPelangganKonfirmasiKeluarActionPerformed
        // TODO add your handling code here:
        addDataKonfirmasiKeluar(1);
    }//GEN-LAST:event_cmbNamaPelangganKonfirmasiKeluarActionPerformed

    private void txtNamaPelangganKonfirmasiKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaPelangganKonfirmasiKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPelangganKonfirmasiKeluarActionPerformed

    private void txtNamaPelangganKonfirmasiKeluarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtNamaPelangganKonfirmasiKeluarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPelangganKonfirmasiKeluarPropertyChange

    private void txtKodeTransaksiKonfirmasiKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeTransaksiKonfirmasiKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeTransaksiKonfirmasiKeluarActionPerformed

    private void txtKodeTransaksiKonfirmasiKeluarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtKodeTransaksiKonfirmasiKeluarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeTransaksiKonfirmasiKeluarPropertyChange

    private void tablePengirimanKonfirmasiKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePengirimanKonfirmasiKeluarMouseClicked
        // TODO add your handling code here:
        if(tablePengirimanKonfirmasiKeluar.getValueAt(tablePengirimanKonfirmasiKeluar.getSelectedRow(), 8).toString().equals("Diterima") ||
                tablePengirimanKonfirmasiKeluar.getValueAt(tablePengirimanKonfirmasiKeluar.getSelectedRow(), 8).toString().equals("Gagal")){
            btnKonfirmasiKonfirmasiKeluar.setEnabled(false);
        }else{
            btnKonfirmasiKonfirmasiKeluar.setEnabled(true);
        }
        modelDetailKarungKonfirmasiKeluar.getDataVector().clear();
        ControllerKonfirmasiKeluar.addKarungKonfirmasiKeluar(modelDetailKarungKonfirmasiKeluar, tablePengirimanKonfirmasiKeluar.getValueAt(tablePengirimanKonfirmasiKeluar.getSelectedRow(), 1).toString());
        modelDetailKarungKonfirmasiKeluar.fireTableDataChanged();

        txtKodeTransaksiKonfirmasiKeluar.setText(tablePengirimanKonfirmasiKeluar.getValueAt(tablePengirimanKonfirmasiKeluar.getSelectedRow(), 1).toString());
        txtNamaPelangganKonfirmasiKeluar.setText(tablePengirimanKonfirmasiKeluar.getValueAt(tablePengirimanKonfirmasiKeluar.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_tablePengirimanKonfirmasiKeluarMouseClicked

    private void rbDiterimaKonfirmasiKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDiterimaKonfirmasiKeluarActionPerformed
        // TODO add your handling code here:
        if (rbDiterimaKonfirmasiKeluar.isSelected()) {
            txtStatusPengirimanKonfirmasiKeluar.setText("Diterima");
        } else {
            txtStatusPengirimanKonfirmasiKeluar.setText("Gagal");
        }
    }//GEN-LAST:event_rbDiterimaKonfirmasiKeluarActionPerformed

    private void btnSemuaKonfirmasiKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSemuaKonfirmasiKeluarActionPerformed
        // TODO add your handling code here:
        addDataKonfirmasiKeluar(0);
    }//GEN-LAST:event_btnSemuaKonfirmasiKeluarActionPerformed

    private void rbGagalKonfirmasiKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGagalKonfirmasiKeluarActionPerformed
        // TODO add your handling code here:
        if (rbDiterimaKonfirmasiKeluar.isSelected()) {
            txtStatusPengirimanKonfirmasiKeluar.setText("Diterima");
        } else {
            txtStatusPengirimanKonfirmasiKeluar.setText("Gagal");
        }
    }//GEN-LAST:event_rbGagalKonfirmasiKeluarActionPerformed

    private void btnKonfirmasiKonfirmasiKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiKonfirmasiKeluarActionPerformed
        // TODO add your handling code here:
        if (txtKodeTransaksiKonfirmasiKeluar.getText().equals("-")) {
            JOptionPane.showMessageDialog(this, "Pilih data yang akan dikonfirmasi dari table pengiriman");
        }
        String status = txtStatusPengirimanKonfirmasiKeluar.getText();
        ControllerPengirimanKonfirmasiKeluar.updateStatus(txtKodeTransaksiKonfirmasiKeluar.getText(), status);
        List<String> pmsn_id = new ArrayList<>();
        String pelanggan = ControllerPelangganKonfirmasiBarang.getIDPelanggan(tablePengirimanKonfirmasiKeluar.getValueAt(tablePengirimanKonfirmasiKeluar.getSelectedRow(), 2).toString());
        pmsn_id = ControllerPengirimanKonfirmasiKeluar.getIDPemesananDetail(txtKodeTransaksiKonfirmasiKeluar.getText());
        for (int i = 0; i < pmsn_id.size(); i++) {
            ControllerPemesananKonfirmasiKeluar.setStatus(pmsn_id.get(i), status);
            if (status.equals("Diterima")) {
                ControllerPelangganKonfirmasiBarang.updateTransaksiKonfirmasiKeluar((ControllerPemesananKonfirmasiKeluar.getPmsn_Total_Uang(pmsn_id.get(i)).toString()), pelanggan );
            }
        }
        JOptionPane.showMessageDialog(this,"Konfirmasi berhasil, Terima Kasih");
        if(cmbNamaPelangganKonfirmasiKeluar.getSelectedItem().toString().equals("- Pilih Pelanggan -")){
            addDataKonfirmasiKeluar(0);
        }else{
            addDataKonfirmasiKeluar(1);
        }
        
    }//GEN-LAST:event_btnKonfirmasiKonfirmasiKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiKonfirmasiBarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiKonfirmasiBarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiKonfirmasiBarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiKonfirmasiBarangKeluar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiKonfirmasiBarangKeluar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonfirmasiKonfirmasiKeluar;
    private javax.swing.JButton btnSemuaKonfirmasiKeluar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbNamaPelangganKonfirmasiKeluar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbDiterimaKonfirmasiKeluar;
    private javax.swing.JRadioButton rbGagalKonfirmasiKeluar;
    private javax.swing.JTable tableKarungKonfirmasiKeluar;
    private javax.swing.JTable tablePengirimanKonfirmasiKeluar;
    private javax.swing.JTextField txtKodeTransaksiKonfirmasiKeluar;
    private javax.swing.JTextField txtNamaPelangganKonfirmasiKeluar;
    private javax.swing.JTextField txtStatusPengirimanKonfirmasiKeluar;
    // End of variables declaration//GEN-END:variables
}
