/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi;

import Controller.CPemesanan;
import Controller.CTableBarang;
import RTClass.Barang;
import RTClass.DetailPemesanan;
import RTClass.Pemesanan;
import connection.DBConnect;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author Polman
 */
public class TransaksiPemesanan extends javax.swing.JFrame {

    /**
     * Creates new form Testing
     */
   //==================================== PEMESANAN VARIABLE =========================================
    DefaultTableModel modelBarangPemesanan = new DefaultTableModel();
    DefaultTableModel modelKeranjangPemesanan = new DefaultTableModel();
    CTableBarang controllerTable = new CTableBarang();
    CPemesanan controllerPemesanan = new CPemesanan();
    DBConnect connection = new DBConnect();
    Pemesanan psn = new Pemesanan();
    Barang barangPemesanan = new Barang();
    CTableBarang ControllerBarang = new CTableBarang();
    int TotalHargaPemesanan = 0;
    int HargaPemesanan = 0;
    DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
    DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
    int TotalBiayaPemesanan = 0;
    
    
    public TransaksiPemesanan() {
        initComponents();
        //================= DEKLARASI PEMESANAN =======================
            
        
        //lblnama.setText(nama);
        //lbljabatan.setText(posisi);
        
        addColumnPemesanan();
        addDataPemesanan();
        
        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(formatRp);
        
        
        tblBarangPemesanan.setModel(modelBarangPemesanan);
        tblKeranjangPemesanan.setModel(modelKeranjangPemesanan);
        
        
        //lebarKolomBarangPemesanan();
        tampilPelangganPemesanan();
        txtNamaPelanggan.setEnabled(false);
        txtJumlahKodiPemesanan.setEnabled(false);
        txtTotalPemesanan.setEnabled(false);
        //lebarKolomKeranjangPemesann();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPemesanan = new javax.swing.JPanel();
        pnlDataBarang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarangPemesanan = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtJumlahKodiPemesanan = new javax.swing.JTextField();
        txtTotalPemesanan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblKeranjangPemesanan = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbPelanggan = new javax.swing.JComboBox<>();
        txtNamaPelanggan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        panelDetailBeli = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtBarangPemesanan = new javax.swing.JTextField();
        Ukuran1 = new javax.swing.JLabel();
        txtJumlahPemesanan = new javax.swing.JSpinner();
        Ukuran2 = new javax.swing.JLabel();
        txtTotalHargaPemesanan = new javax.swing.JTextField();
        btnKeranjangPemesanan = new javax.swing.JButton();
        txtUkuranPemesanan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPemesanan.setPreferredSize(new java.awt.Dimension(1100, 652));
        panelPemesanan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDataBarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblBarangPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBarangPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBarangPemesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBarangPemesanan);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("DATA BARANG");

        javax.swing.GroupLayout pnlDataBarangLayout = new javax.swing.GroupLayout(pnlDataBarang);
        pnlDataBarang.setLayout(pnlDataBarangLayout);
        pnlDataBarangLayout.setHorizontalGroup(
            pnlDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addGroup(pnlDataBarangLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDataBarangLayout.setVerticalGroup(
            pnlDataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelPemesanan.add(pnlDataBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 630));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Total Jumlah Kodi");

        jLabel9.setText("Total Harga");

        txtJumlahKodiPemesanan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtJumlahKodiPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtJumlahKodiPemesananMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtJumlahKodiPemesananMouseEntered(evt);
            }
        });

        txtTotalPemesanan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTotalPemesananMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtTotalPemesananMouseEntered(evt);
            }
        });
        txtTotalPemesanan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotalPemesananKeyReleased(evt);
            }
        });

        jLabel1.setText("Rp. ");

        tblKeranjangPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKeranjangPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKeranjangPemesananMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblKeranjangPemesanan);

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("KERANJANG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txtJumlahKodiPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJumlahKodiPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        panelPemesanan.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 259, 570, -1));

        btnSimpan.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Simpan Pesanan.png"))); // NOI18N
        btnSimpan.setText("Simpan Pesanan");
        btnSimpan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSimpan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        panelPemesanan.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 590, 250, 55));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Nama Toko");

        jLabel3.setText("Nama Pelanggan");

        cmbPelanggan.setBackground(new java.awt.Color(149, 225, 225));
        cmbPelanggan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== Pilih Toko ==" }));
        cmbPelanggan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPelangganItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("DESKRIPSI PEMESANAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbPelanggan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelPemesanan.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 560, -1));

        panelDetailBeli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDetailBeli.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("DESKRIPSI DETAIL PEMESANAN");

        jLabel5.setText("Barang");

        txtBarangPemesanan.setEnabled(false);

        Ukuran1.setText("Jumlah Kodi");

        txtJumlahPemesanan.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        txtJumlahPemesanan.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                txtJumlahPemesananStateChanged(evt);
            }
        });
        txtJumlahPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtJumlahPemesananMouseClicked(evt);
            }
        });
        txtJumlahPemesanan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtJumlahPemesananPropertyChange(evt);
            }
        });

        Ukuran2.setText("Total Harga");

        txtTotalHargaPemesanan.setEnabled(false);
        txtTotalHargaPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalHargaPemesananActionPerformed(evt);
            }
        });

        btnKeranjangPemesanan.setText("Masukkan ke keranjang");
        btnKeranjangPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeranjangPemesananActionPerformed(evt);
            }
        });

        txtUkuranPemesanan.setEnabled(false);

        javax.swing.GroupLayout panelDetailBeliLayout = new javax.swing.GroupLayout(panelDetailBeli);
        panelDetailBeli.setLayout(panelDetailBeliLayout);
        panelDetailBeliLayout.setHorizontalGroup(
            panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailBeliLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetailBeliLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143)
                        .addComponent(btnKeranjangPemesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelDetailBeliLayout.createSequentialGroup()
                        .addGroup(panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBarangPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUkuranPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ukuran1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJumlahPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ukuran2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalHargaPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelDetailBeliLayout.setVerticalGroup(
            panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailBeliLayout.createSequentialGroup()
                .addGroup(panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetailBeliLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKeranjangPemesanan, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ukuran1)
                            .addComponent(Ukuran2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJumlahPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalHargaPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDetailBeliLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(panelDetailBeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBarangPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUkuranPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDetailBeliLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel5)))
                .addGap(12, 12, Short.MAX_VALUE))
        );

        panelPemesanan.add(panelDetailBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 560, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tampilPelangganPemesanan()
    {
         try{
           connection.stat = connection.conn.createStatement();
           String sql = "SELECT pgn_nama_toko,pgn_id FROM Pelanggan";
           connection.result = connection.stat.executeQuery(sql);
           
           while(connection.result.next()){
               cmbPelanggan.addItem(connection.result.getString("pgn_nama_toko"));
           }
           connection.stat.close();
           connection.result.close();
        }
        catch(SQLException ex)
        {
            System.out.println("Terjadi error saat load data pelanggan " + ex);
        }
    }
    public void lebarKolomBarangPemesanan(){ 
        TableColumn column;
        tblBarangPemesanan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tblBarangPemesanan.getColumnModel().getColumn(0); 
        column.setPreferredWidth(100);
        column = tblBarangPemesanan.getColumnModel().getColumn(1); 
        column.setPreferredWidth(100); 
        column = tblBarangPemesanan.getColumnModel().getColumn(2); 
        column.setPreferredWidth(100); 
        column = tblBarangPemesanan.getColumnModel().getColumn(3); 
        column.setPreferredWidth(50);
        column = tblBarangPemesanan.getColumnModel().getColumn(4); 
        column.setPreferredWidth(50);
        column = tblBarangPemesanan.getColumnModel().getColumn(5); 
        column.setPreferredWidth(50);
        column = tblBarangPemesanan.getColumnModel().getColumn(6); 
        column.setPreferredWidth(150);
        column = tblBarangPemesanan.getColumnModel().getColumn(7); 
        column.setPreferredWidth(150);
       
    }
    
    public void lebarKolomKeranjangPemesann(){ 
        TableColumn column;
        tblKeranjangPemesanan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tblKeranjangPemesanan.getColumnModel().getColumn(0); 
        column.setPreferredWidth(100);
        column = tblKeranjangPemesanan.getColumnModel().getColumn(1); 
        column.setPreferredWidth(150); 
        column = tblKeranjangPemesanan.getColumnModel().getColumn(2); 
        column.setPreferredWidth(150); 
        column = tblKeranjangPemesanan.getColumnModel().getColumn(3); 
        column.setPreferredWidth(150);
        column = tblKeranjangPemesanan.getColumnModel().getColumn(4); 
        column.setPreferredWidth(100);
        
    }
    private void addDataPemesanan(){
        modelBarangPemesanan.getDataVector().removeAllElements();

        modelBarangPemesanan.fireTableDataChanged();
        
        modelBarangPemesanan = controllerTable.addDataBarangPemesanan(modelBarangPemesanan);
    }
    private void addColumnPemesanan(){
        modelBarangPemesanan.addColumn("No");
        modelBarangPemesanan.addColumn("Nama Barang");
        modelBarangPemesanan.addColumn("Jenis Barang");
        modelBarangPemesanan.addColumn("Ukuran");
        modelBarangPemesanan.addColumn("Bahan");
        modelBarangPemesanan.addColumn("Stok");        
        modelBarangPemesanan.addColumn("Harga Jual Satuan");
        modelBarangPemesanan.addColumn("Harga Jual Kodian");

        modelKeranjangPemesanan.addColumn("No");
        modelKeranjangPemesanan.addColumn("Barang");
        modelKeranjangPemesanan.addColumn("Ukuran");
        modelKeranjangPemesanan.addColumn("Jumlah");
        modelKeranjangPemesanan.addColumn("Harga");
    }
    private void txtTotalPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTotalPemesananMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTotalPemesananMouseClicked

    private void txtTotalPemesananMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTotalPemesananMouseEntered
        // TODO add your handling code here:
        double temp1,temp2,temp3, total = 0.0;

        int i = tblKeranjangPemesanan.getSelectedRow();
        if(i == -1){
            return;
        }
        int j = tblKeranjangPemesanan.getModel().getRowCount();

        for (int k = 0; k < j; k++){
            temp1 = (Double.parseDouble((String) tblKeranjangPemesanan.getValueAt(k, 3)));
            temp2 = (Double.parseDouble((String) tblKeranjangPemesanan.getValueAt(k, 5)));
            temp3 = temp1 * temp2;
            total = total + temp3;
        }
        txtTotalPemesanan.setText(String.valueOf(total));
    }//GEN-LAST:event_txtTotalPemesananMouseEntered

    private void txtTotalPemesananKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalPemesananKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTotalPemesananKeyReleased

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(cmbPelanggan.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Isi data dengan benar!");
            return;
        }
        int stock, stock2 = 0;
        SimpleDateFormat formatDate = new SimpleDateFormat("yyyyMMdd");
        String IdPelanggan = (String) cmbPelanggan.getSelectedItem();
        //String namaKry = lblnama.getText();

        if (cmbPelanggan.getSelectedItem().equals("== Pilih Pelanggan ==") || txtTotalPemesanan.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong!");
        }
        else{

            try{
                connection.stat = connection.conn.createStatement();
                String sql = "SELECT pgn_id,pgn_nama_toko FROM Pelanggan WHERE pgn_nama_toko = '" + cmbPelanggan.getSelectedItem() + "'";
                connection.result = connection.stat.executeQuery(sql);

                while (connection.result.next()){
                    IdPelanggan = connection.result.getString("pgn_id");
                }

                connection.stat = connection.conn.createStatement();
            //    String sql1 = "SELECT kry_id,kry_nama FROM Karyawan WHERE kry_nama = '" + lblnama.getText()+ "'";
           //     connection.result = connection.stat.executeQuery(sql1);

                while (connection.result.next()){
            //        namaKry = connection.result.getString("kry_id");
                }

                psn.setPmsn_id(formatDate.format(new Date()) +"-"+ controllerPemesanan.getLastID());
                psn.setPgn_id(Integer.parseInt(IdPelanggan));
                SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                Date date = new Date();
                psn.setPmsn_tgl_transaksi(date);
                psn.setPmsn_jumlah_barang((Integer.parseInt(txtJumlahKodiPemesanan.getText()) * 20));
                psn.setPmsn_jumlah_kodi(Integer.parseInt(txtJumlahKodiPemesanan.getText()));
                psn.setPmsn_total_uang(Double.parseDouble(String.valueOf(TotalBiayaPemesanan)));
                psn.setPmsn_Status("Disiapkan");
                psn.setKry_id("202007010002");
                //psn.setKry_id(kry_id);
                controllerPemesanan.simpanPemesanan(psn);

                

                
                DetailPemesanan detailPemesanan = new DetailPemesanan();
                detailPemesanan.setPmsn_id(psn.getPmsn_id());
                for(int i = 0 ; i < tblKeranjangPemesanan.getRowCount();i++){
                    barangPemesanan = ControllerBarang.getDatabyNamaUkuran(tblKeranjangPemesanan.getValueAt(i, 1).toString(), tblKeranjangPemesanan.getValueAt(i, 2).toString());
                    detailPemesanan.setB_id(Integer.toString(barangPemesanan.getID_Barang()));
                    detailPemesanan.setDetail_jumlah_kodi((int)tblKeranjangPemesanan.getValueAt(i, 3));
                    detailPemesanan.setDetail_jumlah_barang(((int)tblKeranjangPemesanan.getValueAt(i, 3)) * 20);
                    detailPemesanan.setDetail_total_uang((int)tblKeranjangPemesanan.getValueAt(i, 4));
                    controllerPemesanan.simpanDetailPemesanan(detailPemesanan);
                }
                
                
                
                JOptionPane.showMessageDialog(this, "Berhasil menambahkan pesanan..");
                clearPesananPemesanan();

            }
            catch (SQLException ex){
                System.out.println("Terjadi error saat insert " + ex);
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed
    public void clearPesananPemesanan(){
        cmbPelanggan.setSelectedIndex(0);
        txtNamaPelanggan.setText("");
        txtJumlahKodiPemesanan.setText("");
        txtTotalPemesanan.setText("");
    }
    
    
    public void getSumJumlahKodi()
    {
        int sum = 0;
        for(int i = 0; i < tblKeranjangPemesanan.getRowCount(); i++)
        {
            sum = sum + Integer.parseInt(tblKeranjangPemesanan.getValueAt(i, 5).toString());
        }
        
        txtJumlahKodiPemesanan.setText(Integer.toString(sum));
    }
    private void txtJumlahKodiPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJumlahKodiPemesananMouseClicked
        // TODO add your handling code here:
        //        getSumJumlahKodi();
    }//GEN-LAST:event_txtJumlahKodiPemesananMouseClicked

    private void txtJumlahKodiPemesananMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJumlahKodiPemesananMouseEntered
        // TODO add your handling code here:
        //getSumJumlahKodi();
    }//GEN-LAST:event_txtJumlahKodiPemesananMouseEntered

    private void cmbPelangganItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPelangganItemStateChanged
        // TODO add your handling code here:
        try{
            DBConnect c = new DBConnect();
            c.stat = c.conn.createStatement();
            String sql = "SELECT * FROM Pelanggan";
            c.result = c.stat.executeQuery(sql);

            while (c.result.next()) {
                if(c.result.getString("pgn_nama_toko").equals(cmbPelanggan.getSelectedItem().toString())){
                    txtNamaPelanggan.setText(c.result.getString("pgn_nama"));
                }
            }
            c.stat.close();
            c.result.close();

        } catch (SQLException ex){
            System.out.println("Terjadi error"+ex);
        }
    }//GEN-LAST:event_cmbPelangganItemStateChanged

    private void txtJumlahPemesananStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_txtJumlahPemesananStateChanged
        // TODO add your handling code here:
        try{
            int jumlah = Integer.parseInt(txtJumlahPemesanan.getValue().toString());
            TotalHargaPemesanan = jumlah * HargaPemesanan;
            txtTotalHargaPemesanan.setText(kursIndonesia.format((TotalHargaPemesanan)));

            //System.out.println(total);
        }catch(Exception ex){
            System.out.println("Error cuy txtJumlahPropertyChange "+ex);
        }
    }//GEN-LAST:event_txtJumlahPemesananStateChanged

    private void txtJumlahPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJumlahPemesananMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txtJumlahPemesananMouseClicked

    private void txtJumlahPemesananPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtJumlahPemesananPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_txtJumlahPemesananPropertyChange

    private void txtTotalHargaPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalHargaPemesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalHargaPemesananActionPerformed

    private void btnKeranjangPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeranjangPemesananActionPerformed
        // TODO add your handling code here:
        if(txtBarangPemesanan.getText().equals("")){
            return;
        }
        for(int i = 0 ; i < modelKeranjangPemesanan.getRowCount() ; i ++){
            if(modelKeranjangPemesanan.getValueAt(i, 1).toString().equals(txtBarangPemesanan.getText()) && modelKeranjangPemesanan.getValueAt(i, 2).toString().equals(txtUkuranPemesanan.getText())){
                modelKeranjangPemesanan.removeRow(i);
            }
        }
        hitungTotalPemesanan();
        hitungKodiPemesanan();
        Object[] rowData = new Object[]{modelKeranjangPemesanan.getRowCount()+1,txtBarangPemesanan.getText(),txtUkuranPemesanan.getText(), txtJumlahPemesanan.getValue(),TotalHargaPemesanan};
        modelKeranjangPemesanan.addRow(rowData);
        clearPemesanan();
        
    }//GEN-LAST:event_btnKeranjangPemesananActionPerformed
    private void clearPemesanan(){
        txtBarangPemesanan.setText("");
        txtJumlahPemesanan.setValue(1);
        txtTotalHargaPemesanan.setText("");
        txtUkuranPemesanan.setText("");
        hitungKodiPemesanan();
        hitungTotalPemesanan();
    }
    private void hitungTotalPemesanan(){
        int total = 0;
        for(int i = 0 ; i < modelKeranjangPemesanan.getRowCount();i++){
            total = total +(int) modelKeranjangPemesanan.getValueAt(i, 4);
        }
        txtTotalPemesanan.setText(kursIndonesia.format(total));
        TotalBiayaPemesanan = total;
    }
    private void hitungKodiPemesanan(){
        int total = 0;
        for(int i = 0 ; i < modelKeranjangPemesanan.getRowCount();i++){
            total = total +(int) modelKeranjangPemesanan.getValueAt(i, 3);
        }
        txtJumlahKodiPemesanan.setText(Integer.toString(total));
        //txtJumlahBarangPemesanan.setText(Integer.toString(total*20));
    }
    private void tblBarangPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBarangPemesananMouseClicked
        // TODO add your handling code here:
        barangPemesanan = ControllerBarang.getSelectedRowBarangPemasokkan(tblBarangPemesanan);
        
        txtBarangPemesanan.setText(barangPemesanan.getNama_Barang());
        txtUkuranPemesanan.setText(barangPemesanan.getUkuran_Barang());
        
        TotalHargaPemesanan = (int) Math.round(barangPemesanan.getHargaKodian_Barang());
        HargaPemesanan = (int) Math.round(barangPemesanan.getHargaKodian_Barang());
        txtTotalHargaPemesanan.setText(kursIndonesia.format((int) Math.round(barangPemesanan.getHargaKodian_Barang())));
    }//GEN-LAST:event_tblBarangPemesananMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        modelKeranjangPemesanan.getDataVector().removeAllElements();

        modelKeranjangPemesanan.fireTableDataChanged();
        clearPemesanan();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblKeranjangPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKeranjangPemesananMouseClicked
        // TODO add your handling code here:
        
        txtBarangPemesanan.setText((String) tblKeranjangPemesanan.getValueAt(tblKeranjangPemesanan.getSelectedRow(), 1));
        txtUkuranPemesanan.setText((String) tblKeranjangPemesanan.getValueAt(tblKeranjangPemesanan.getSelectedRow(), 2));
        
        
        TotalHargaPemesanan = (int)(tblKeranjangPemesanan.getValueAt(tblKeranjangPemesanan.getSelectedRow(), 4));
        HargaPemesanan = (TotalHargaPemesanan / (int) tblKeranjangPemesanan.getValueAt(tblKeranjangPemesanan.getSelectedRow(), 3));
        txtTotalHargaPemesanan.setText(kursIndonesia.format((int) Math.round(HargaPemesanan)));
    }//GEN-LAST:event_tblKeranjangPemesananMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiPemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ukuran1;
    private javax.swing.JLabel Ukuran2;
    private javax.swing.JButton btnKeranjangPemesanan;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmbPelanggan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelDetailBeli;
    private javax.swing.JPanel panelPemesanan;
    private javax.swing.JPanel pnlDataBarang;
    private javax.swing.JTable tblBarangPemesanan;
    private javax.swing.JTable tblKeranjangPemesanan;
    private javax.swing.JTextField txtBarangPemesanan;
    private javax.swing.JTextField txtJumlahKodiPemesanan;
    private javax.swing.JSpinner txtJumlahPemesanan;
    private javax.swing.JTextField txtNamaPelanggan;
    private javax.swing.JTextField txtTotalHargaPemesanan;
    private javax.swing.JTextField txtTotalPemesanan;
    private javax.swing.JTextField txtUkuranPemesanan;
    // End of variables declaration//GEN-END:variables
}
