/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi;

import Controller.CPelanggan;
import Controller.CPemasokkan;
import Controller.CPembayaran;
import Controller.CPemesanan;
import Controller.CSupplier;
import Controller.CTable;
import RTClass.Pelanggan;
import RTClass.Pembayaran;
import connection.DBConnect;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rizky
 */
public class TransaksiPembayaranPelanggan extends javax.swing.JFrame {

    // =================================== DEKLARASI VARIABLE DAN PROSEDUR PEMBAYARAN PELANGGAN ===========================
    public String kry_id = "";
    Pelanggan pelangganPembayarnPelanggan = new Pelanggan();
    CPelanggan controllerPelangganPembayaranPelanggan = new CPelanggan();
    CTable controlTablePembayaranPelanggan = new CTable();
    private DefaultTableModel modelPelangganPembayaranPelanggan = new DefaultTableModel();
    CPembayaran ControllerPembayaranPembayaranPelanggan = new CPembayaran();
    CPemesanan ControllerPemesananPembayaranPelanggan = new CPemesanan();
    
    DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
    DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
    /**
     * Creates new form TransaksiPembayaranPelanggan
     */
    public TransaksiPembayaranPelanggan() {
        initComponents();
        
        addColumnPembayaranPelanggan();
        addComboBoxPembayaranPelanggan();
        tablePelanggan.setModel(modelPelangganPembayaranPelanggan);
    }
    
    private void addComboBoxPembayaranPelanggan(){
        try {
            DBConnect connection = new DBConnect();
            connection.stat = connection.conn.createStatement();
            String query = "select * from Pelanggan";
            connection.result = connection.stat.executeQuery(query);
            
            while (connection.result.next()) {
                
                cmbPelanggan.addItem(connection.result.getString("pgn_nama"));
            }
            connection.stat.close();
            connection.result.close();
        } catch (Exception e) {
            System.out.println("Gagal addDataPelanggan!\n" + e.toString());
        }
    }

    private void addColumnPembayaranPelanggan() {
        modelPelangganPembayaranPelanggan.addColumn("No");
        modelPelangganPembayaranPelanggan.addColumn("Nama");
        modelPelangganPembayaranPelanggan.addColumn("Toko");
        modelPelangganPembayaranPelanggan.addColumn("No HP");
        modelPelangganPembayaranPelanggan.addColumn("Email");
        modelPelangganPembayaranPelanggan.addColumn("Alamat");
        modelPelangganPembayaranPelanggan.addColumn("Pasar");
        modelPelangganPembayaranPelanggan.addColumn("Transaksi");
        modelPelangganPembayaranPelanggan.addColumn("Pembayaran");
        modelPelangganPembayaranPelanggan.addColumn("Hutang");
    }
    
    private void clearPembayaranPelanggan() {

        txtNamaToko.setText("-");
        txtNamaPelanggan.setText("-");
        txtJumlahTransaksiPelanggan.setText("0");
        txtHutangPelanggan.setText(kursIndonesia.format(0));

        txtSisaHutang.setText(kursIndonesia.format(0));
        txtBayar.setText(kursIndonesia.format(0));
        txtKembalian.setText(kursIndonesia.format(0));
        

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPembayaranPelanggan = new javax.swing.JPanel();
        panelDaftarBarangMasuk = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePelanggan = new javax.swing.JTable();
        cmbPelanggan = new javax.swing.JComboBox<>();
        panelDeskripsiBarangMasuk = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNamaToko = new javax.swing.JTextField();
        txtJumlahTransaksiPelanggan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHutangPelanggan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSisaHutang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lblKeteranganPembayaran = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNamaPelanggan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelDaftarBarangMasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("DAFTAR PELANGGAN");

        tablePelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePelanggan);

        cmbPelanggan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Pelanggan -" }));
        cmbPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPelangganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDaftarBarangMasukLayout = new javax.swing.GroupLayout(panelDaftarBarangMasuk);
        panelDaftarBarangMasuk.setLayout(panelDaftarBarangMasukLayout);
        panelDaftarBarangMasukLayout.setHorizontalGroup(
            panelDaftarBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarBarangMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDaftarBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
                    .addGroup(panelDaftarBarangMasukLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelDaftarBarangMasukLayout.setVerticalGroup(
            panelDaftarBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarBarangMasukLayout.createSequentialGroup()
                .addGroup(panelDaftarBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );

        panelDeskripsiBarangMasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDeskripsiBarangMasuk.setPreferredSize(new java.awt.Dimension(1100, 185));
        panelDeskripsiBarangMasuk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("DESKRIPSI TRANSAKSI PEMBAYARAN PEMASOKKAN");
        panelDeskripsiBarangMasuk.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 380, 33));

        jLabel2.setText("Nama Toko");
        panelDeskripsiBarangMasuk.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 50, 99, -1));

        txtNamaToko.setText("-");
        panelDeskripsiBarangMasuk.add(txtNamaToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 240, -1));

        txtJumlahTransaksiPelanggan.setText("-");
        panelDeskripsiBarangMasuk.add(txtJumlahTransaksiPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 240, -1));

        jLabel3.setText("Jumlah transaksi");
        panelDeskripsiBarangMasuk.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel5.setText("Hutang");
        panelDeskripsiBarangMasuk.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 99, -1));

        txtHutangPelanggan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHutangPelanggan.setText("Rp. 0,00");
        txtHutangPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHutangPelangganActionPerformed(evt);
            }
        });
        panelDeskripsiBarangMasuk.add(txtHutangPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 240, -1));

        jLabel6.setText("Kembali ");
        panelDeskripsiBarangMasuk.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        txtBayar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBayar.setText("0");
        txtBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBayarKeyReleased(evt);
            }
        });
        panelDeskripsiBarangMasuk.add(txtBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 179, -1));

        jLabel9.setText("Rp");
        panelDeskripsiBarangMasuk.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        jLabel10.setText("Sisa hutang pada pelanggan");
        panelDeskripsiBarangMasuk.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        txtSisaHutang.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSisaHutang.setText("Rp. 0,00");
        panelDeskripsiBarangMasuk.add(txtSisaHutang, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 200, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("KETERANGAN PEMBAYARAN");
        panelDeskripsiBarangMasuk.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        lblKeteranganPembayaran.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblKeteranganPembayaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeteranganPembayaran.setText("[Keterangan]");
        lblKeteranganPembayaran.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDeskripsiBarangMasuk.add(lblKeteranganPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 32, 428, 55));

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        panelDeskripsiBarangMasuk.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 100, 209, -1));

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });
        panelDeskripsiBarangMasuk.add(btnBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 200, -1));

        jLabel11.setText("Banyak uang dibayar");
        panelDeskripsiBarangMasuk.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        txtKembalian.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtKembalian.setText("0");
        txtKembalian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKembalianKeyReleased(evt);
            }
        });
        panelDeskripsiBarangMasuk.add(txtKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 179, -1));

        jLabel13.setText("Rp");
        panelDeskripsiBarangMasuk.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jLabel4.setText("Nama Pelanggan");
        panelDeskripsiBarangMasuk.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txtNamaPelanggan.setText("-");
        panelDeskripsiBarangMasuk.add(txtNamaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 240, -1));

        javax.swing.GroupLayout panelPembayaranPelangganLayout = new javax.swing.GroupLayout(panelPembayaranPelanggan);
        panelPembayaranPelanggan.setLayout(panelPembayaranPelangganLayout);
        panelPembayaranPelangganLayout.setHorizontalGroup(
            panelPembayaranPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1119, Short.MAX_VALUE)
            .addGroup(panelPembayaranPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPembayaranPelangganLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(panelPembayaranPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelPembayaranPelangganLayout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(panelDeskripsiBarangMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(panelDaftarBarangMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelPembayaranPelangganLayout.setVerticalGroup(
            panelPembayaranPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
            .addGroup(panelPembayaranPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelPembayaranPelangganLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelDaftarBarangMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)
                    .addComponent(panelDeskripsiBarangMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPembayaranPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPembayaranPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablePelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePelangganMouseClicked
        // TODO add your handling code here:
        clearPembayaranPelanggan();
        pelangganPembayarnPelanggan = controlTablePembayaranPelanggan.getSelectedRowPelanggan(tablePelanggan);
        
        txtNamaToko.setText(pelangganPembayarnPelanggan.getPgn_nama_toko());
        txtNamaPelanggan.setText(pelangganPembayarnPelanggan.getPgn_nama());
        txtJumlahTransaksiPelanggan.setText(Integer.toString(pelangganPembayarnPelanggan.getPgn_jumlah_transaksi()));
        txtHutangPelanggan.setText(kursIndonesia.format(pelangganPembayarnPelanggan.getPgn_total_hutang()));
        int status = pelangganPembayarnPelanggan.getPgn_uang_transaksi();

        if ( pelangganPembayarnPelanggan.getPgn_total_hutang() == 0){
            lblKeteranganPembayaran.setText("LUNAS");
            if (lblKeteranganPembayaran.getText().equals("LUNAS"))
            {
                btnBayar.setEnabled(false);
            }
        }
        else{
            lblKeteranganPembayaran.setText("BELUM LUNAS");
        }
    }//GEN-LAST:event_tablePelangganMouseClicked

    private void cmbPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPelangganActionPerformed
        // TODO add your handling code here:
        modelPelangganPembayaranPelanggan.getDataVector().removeAllElements();

        modelPelangganPembayaranPelanggan.fireTableDataChanged();
        clearPembayaranPelanggan();
        controlTablePembayaranPelanggan.addDataPelanggan(modelPelangganPembayaranPelanggan,(String) cmbPelanggan.getSelectedItem());
    }//GEN-LAST:event_cmbPelangganActionPerformed

    private void txtBayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBayarKeyReleased
        // TODO add your handling code here:

        if (txtBayar.getText().equals("")) {
            txtSisaHutang.setText(txtHutangPelanggan.getText());
            return;
        }

        try {

            txtSisaHutang.setText(kursIndonesia.format(((long) kursIndonesia.parse(txtHutangPelanggan.getText())) - Long.parseLong(txtBayar.getText())));
            txtKembalian.setText(kursIndonesia.format((Long.parseLong(txtBayar.getText())) - (long) kursIndonesia.parse(txtHutangPelanggan.getText())));

        } catch (Exception ex) {

        }
    }//GEN-LAST:event_txtBayarKeyReleased

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    private void addDataPelanggan(){
        
        modelPelangganPembayaranPelanggan.getDataVector().removeAllElements();

        modelPelangganPembayaranPelanggan.fireTableDataChanged();
        controlTablePembayaranPelanggan.addDataPemasok(modelPelangganPembayaranPelanggan,(String) cmbPelanggan.getSelectedItem());
    }
    
    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat date = new SimpleDateFormat("ddMMyyyy");

        Pembayaran pembayaran = new Pembayaran();
        pembayaran.setPmby_id(ControllerPembayaranPembayaranPelanggan.getLastID());
        pembayaran.setPgn_id(controlTablePembayaranPelanggan.getPelangganId((String)cmbPelanggan.getSelectedItem()));
        pembayaran.setKry_id("202006290001");
        pembayaran.setPmby_tgl_transaksi(new Date());
        pembayaran.setPmby_uang_masuk(Integer.valueOf(txtBayar.getText()));

        ControllerPembayaranPembayaranPelanggan.simpanPembayaranPemasok(pembayaran);
        try {
            controllerPelangganPembayaranPelanggan.updateTransaksiPembayaranPelanggan(Long.parseLong(txtBayar.getText()), Long.parseLong((kursIndonesia.parse(txtSisaHutang.getText())).toString()), pelangganPembayarnPelanggan.getPgn_id().toString());

            controlTablePembayaranPelanggan.addDataPemasok(modelPelangganPembayaranPelanggan,(String) cmbPelanggan.getSelectedItem());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Tidak dapat menyimpan ke pelangganPembayarnPelanggan!");
        }

        JOptionPane.showMessageDialog(this, "Pembayaran berhasil....");
        addDataPelanggan();
        clearPembayaranPelanggan();
        cmbPelanggan.setSelectedIndex(0);
        lblKeteranganPembayaran.setText("[Keterangan]");
    }//GEN-LAST:event_btnBayarActionPerformed

    
    private void txtKembalianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKembalianKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKembalianKeyReleased

    private void txtHutangPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHutangPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHutangPelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiPembayaranPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiPembayaranPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiPembayaranPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiPembayaranPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiPembayaranPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBayar;
    private javax.swing.JComboBox<String> cmbPelanggan;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKeteranganPembayaran;
    private javax.swing.JPanel panelDaftarBarangMasuk;
    private javax.swing.JPanel panelDeskripsiBarangMasuk;
    private javax.swing.JPanel panelPembayaranPelanggan;
    private javax.swing.JTable tablePelanggan;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtHutangPelanggan;
    private javax.swing.JTextField txtJumlahTransaksiPelanggan;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtNamaPelanggan;
    private javax.swing.JTextField txtNamaToko;
    private javax.swing.JTextField txtSisaHutang;
    // End of variables declaration//GEN-END:variables
}
