/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi;

import Controller.CPemasokkan;
import Controller.CPembayaran;
import Controller.CSupplier;
import Controller.CTable;
import RTClass.Pemasok;
import RTClass.Pembayaran;
import connection.DBConnect;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rizky
 */
public class TransaksiPembayaranPemasok extends javax.swing.JFrame {

    /**
     * Creates new form TransaksiPembayaranPemasok
     */
    public String kry_id = "";
    Pemasok pemasok = new Pemasok();
    CSupplier controllerpemasok = new CSupplier();
    CTable controllerTable = new CTable();
    private DefaultTableModel modelPemasok = new DefaultTableModel();
    CPembayaran ControllerPembayaran = new CPembayaran();
    CPemasokkan ControllerPemasokkan = new CPemasokkan();
    
    DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
    DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
    
    public TransaksiPembayaranPemasok() {
        initComponents();
        
        addColumn();
        addComboBox();
        tablePemasok.setModel(modelPemasok);
    }
    
    private void addComboBox(){
        try {
            DBConnect connection = new DBConnect();
            connection.stat = connection.conn.createStatement();
            String query = "select * from Pemasok";
            connection.result = connection.stat.executeQuery(query);
            
            while (connection.result.next()) {
                
                cmbPemasok.addItem(connection.result.getString("pms_nama"));
            }
            connection.stat.close();
            connection.result.close();
        } catch (Exception e) {
            System.out.println("Gagal111 addDataPemasok!\n" + e.toString());
        }
    }
    
    private void addColumn() {
        modelPemasok.addColumn("No");
        modelPemasok.addColumn("Nama");
        modelPemasok.addColumn("Alamat");
        modelPemasok.addColumn("No HP");
        modelPemasok.addColumn("Transaksi");
        modelPemasok.addColumn("Pembayaran");
        modelPemasok.addColumn("Hutang");
    }
    
    private void addData() {
        modelPemasok.getDataVector().removeAllElements();

        modelPemasok.fireTableDataChanged();

        modelPemasok = controllerTable.addDataPemasok(modelPemasok);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPembayaranPemasok = new javax.swing.JPanel();
        panelDaftarBarangMasuk = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePemasok = new javax.swing.JTable();
        cmbPemasok = new javax.swing.JComboBox<>();
        panelDeskripsiBarangMasuk = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNamaPemasok = new javax.swing.JTextField();
        txtJumlahTransaksiPemasok = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHutangPemasok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtBayar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSisaHutang = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lblKeteranganPembayaran = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPembayaranPemasok.setMinimumSize(new java.awt.Dimension(1100, 652));
        panelPembayaranPemasok.setPreferredSize(new java.awt.Dimension(1100, 652));
        panelPembayaranPemasok.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDaftarBarangMasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("DAFTAR PEMASOK");

        tablePemasok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePemasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePemasokMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePemasok);

        cmbPemasok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Pemasok -" }));
        cmbPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPemasokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDaftarBarangMasukLayout = new javax.swing.GroupLayout(panelDaftarBarangMasuk);
        panelDaftarBarangMasuk.setLayout(panelDaftarBarangMasukLayout);
        panelDaftarBarangMasukLayout.setHorizontalGroup(
            panelDaftarBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarBarangMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDaftarBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1068, Short.MAX_VALUE)
                    .addGroup(panelDaftarBarangMasukLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelDaftarBarangMasukLayout.setVerticalGroup(
            panelDaftarBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarBarangMasukLayout.createSequentialGroup()
                .addGroup(panelDaftarBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );

        panelPembayaranPemasok.add(panelDaftarBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1100, 400));

        panelDeskripsiBarangMasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDeskripsiBarangMasuk.setPreferredSize(new java.awt.Dimension(1100, 185));
        panelDeskripsiBarangMasuk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("DESKRIPSI TRANSAKSI PEMBAYARAN PEMASOKKAN");
        panelDeskripsiBarangMasuk.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 380, 33));

        jLabel2.setText("Nama");
        panelDeskripsiBarangMasuk.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 50, 99, -1));

        txtNamaPemasok.setText("-");
        panelDeskripsiBarangMasuk.add(txtNamaPemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 240, -1));

        txtJumlahTransaksiPemasok.setText("-");
        panelDeskripsiBarangMasuk.add(txtJumlahTransaksiPemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 240, -1));

        jLabel3.setText("Jumlah transaksi");
        panelDeskripsiBarangMasuk.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 86, -1, -1));

        jLabel5.setText("Hutang");
        panelDeskripsiBarangMasuk.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 99, -1));

        txtHutangPemasok.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHutangPemasok.setText("Rp. 0,00");
        panelDeskripsiBarangMasuk.add(txtHutangPemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 240, -1));

        jLabel6.setText("Kembali ");
        panelDeskripsiBarangMasuk.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        txtBayar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBayar.setText("0");
        txtBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBayarKeyReleased(evt);
            }
        });
        panelDeskripsiBarangMasuk.add(txtBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 179, -1));

        jLabel9.setText("Rp");
        panelDeskripsiBarangMasuk.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        jLabel10.setText("Sisa hutang pada pemasok");
        panelDeskripsiBarangMasuk.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        txtSisaHutang.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSisaHutang.setText("Rp. 0,00");
        panelDeskripsiBarangMasuk.add(txtSisaHutang, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 200, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setText("KETERANGAN PEMBAYARAN");
        panelDeskripsiBarangMasuk.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        lblKeteranganPembayaran.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblKeteranganPembayaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKeteranganPembayaran.setText("[Keterangan]");
        lblKeteranganPembayaran.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelDeskripsiBarangMasuk.add(lblKeteranganPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 32, 428, 55));

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        panelDeskripsiBarangMasuk.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 100, 209, -1));

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });
        panelDeskripsiBarangMasuk.add(btnBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 200, -1));

        jLabel11.setText("Banyak uang dibayar");
        panelDeskripsiBarangMasuk.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        txtKembalian.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtKembalian.setText("0");
        txtKembalian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKembalianKeyReleased(evt);
            }
        });
        panelDeskripsiBarangMasuk.add(txtKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 179, -1));

        jLabel13.setText("Rp");
        panelDeskripsiBarangMasuk.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        panelPembayaranPemasok.add(panelDeskripsiBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 1100, 210));

        getContentPane().add(panelPembayaranPemasok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablePemasokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePemasokMouseClicked
        // TODO add your handling code here:
        clear();
        pemasok = controllerTable.getSelectedRowPemasok(tablePemasok);
        txtNamaPemasok.setText(pemasok.getPms_nama());
        txtJumlahTransaksiPemasok.setText(Integer.toString(pemasok.getPms_jumlah_transaksi()));
        txtHutangPemasok.setText(kursIndonesia.format(pemasok.getPms_total_hutang()));
        int status = pemasok.getPms_uang_transaksi();
        
        if ( pemasok.getPms_total_hutang() == 0){
            lblKeteranganPembayaran.setText("LUNAS");
            if (lblKeteranganPembayaran.getText().equals("LUNAS"))
            {
                btnBayar.setEnabled(false);
            }
        }
        else{
            lblKeteranganPembayaran.setText("BELUM LUNAS");
        }

    }//GEN-LAST:event_tablePemasokMouseClicked

    private void txtBayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBayarKeyReleased
        // TODO add your handling code here:
        
        if (txtBayar.getText().equals("")) {
            txtSisaHutang.setText(txtHutangPemasok.getText());
            return;
        }

        try {
           
            txtSisaHutang.setText(kursIndonesia.format(((long) kursIndonesia.parse(txtHutangPemasok.getText())) - Long.parseLong(txtBayar.getText())));
            txtKembalian.setText(kursIndonesia.format((Long.parseLong(txtBayar.getText())) - (long) kursIndonesia.parse(txtHutangPemasok.getText())));
            
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_txtBayarKeyReleased

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat date = new SimpleDateFormat("ddMMyyyy");
        
        Pembayaran pembayaran = new Pembayaran();
        pembayaran.setBpmsk_id(ControllerPembayaran.getLastID());
        pembayaran.setPms_id(controllerTable.getPemasokId((String)cmbPemasok.getSelectedItem()));
        pembayaran.setKry_id("202006290001");
        pembayaran.setBpmsk_tgl_transaksi(new Date());
        pembayaran.setBpmsk_uang_dibayar(Integer.valueOf(txtBayar.getText()));
        
        ControllerPembayaran.simpanPembayaranPemasok(pembayaran);
        try {
            controllerpemasok.updateTransaksiPembayaran(Long.parseLong(txtBayar.getText()), Long.parseLong((kursIndonesia.parse(txtSisaHutang.getText())).toString()), pemasok.getPms_id().toString());
            
            controllerTable.addDataPemasok(modelPemasok,(String) cmbPemasok.getSelectedItem());
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Tidak dapat menyimpan ke pemasok!");
        }
        
        JOptionPane.showMessageDialog(this, "Pembayaran berhasil....");
        addDataPemasok();
        clear();
        cmbPemasok.setSelectedIndex(0);
        lblKeteranganPembayaran.setText("[Keterangan]");
    }//GEN-LAST:event_btnBayarActionPerformed

    private void addDataPemasok(){
        
        modelPemasok.getDataVector().removeAllElements();

        modelPemasok.fireTableDataChanged();
        controllerTable.addDataPemasok(modelPemasok,(String) cmbPemasok.getSelectedItem());
    }
    private void clear() {

        txtNamaPemasok.setText("-");
        txtJumlahTransaksiPemasok.setText("0");
        txtHutangPemasok.setText(kursIndonesia.format(0));

        txtSisaHutang.setText(kursIndonesia.format(0));
        txtBayar.setText(kursIndonesia.format(0));
        txtKembalian.setText(kursIndonesia.format(0));

    }
    
    private void cmbPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPemasokActionPerformed
        // TODO add your handling code here:
        modelPemasok.getDataVector().removeAllElements();

        modelPemasok.fireTableDataChanged();
        clear();
        controllerTable.addDataPemasok(modelPemasok,(String) cmbPemasok.getSelectedItem());
    }//GEN-LAST:event_cmbPemasokActionPerformed

    private void txtKembalianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKembalianKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKembalianKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiPembayaranPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiPembayaranPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiPembayaranPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiPembayaranPemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiPembayaranPemasok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBayar;
    private javax.swing.JComboBox<String> cmbPemasok;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblKeteranganPembayaran;
    private javax.swing.JPanel panelDaftarBarangMasuk;
    private javax.swing.JPanel panelDeskripsiBarangMasuk;
    private javax.swing.JPanel panelPembayaranPemasok;
    private javax.swing.JTable tablePemasok;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtHutangPemasok;
    private javax.swing.JTextField txtJumlahTransaksiPemasok;
    private javax.swing.JTextField txtKembalian;
    private javax.swing.JTextField txtNamaPemasok;
    private javax.swing.JTextField txtSisaHutang;
    // End of variables declaration//GEN-END:variables
}
